#!/anaconda3/bin/python3.7
# -*- coding: utf-8 -*-
# config.py
# Bernard Schroffenegger
# 20th of October, 2019

import os
basedir = os.path.abspath(os.path.dirname(__file__))

class Config(object):

    APP_NAME = "KoKoS-Bullinger"
    ADMIN = 'Admin'
    ADMINS = [ADMIN, 'mvolk', 'Patricia']
    VIP = [ADMIN, 'mvolk', 'Patricia', 'Judith Steiniger', 'Peter Rechsteiner', 'PeterOpitz', 'tschudi1505']

    SECRET_KEY = os.environ.get('SECRET_KEY') or 'the010gy_sucks:P'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    BULLINGER_UI_PATH = os.environ.get('BULLINGER_UI_PATH') or 'http://bullinger.raphaelm.ch/'
    BULLINGER_MAP_PATH = os.environ.get('BULLINGER_MAP_PATH') or 'http://bullinger-map.raphaelm.ch/'

    # status cards
    S_OPEN = 'offen'
    S_UNKNOWN = 'unklar'
    S_FINISHED = 'abgeschlossen'
    S_INVALID = 'ungültig'

    # null values
    SD = 's.d.'  # sine die
    SN = 's.n.'  # sine nomine
    SL = 's.l.'  # sine loco
    NONE = '-'  # language stats

    BASIC_AUTH_USERNAME = 'Admin'  # fake
    BASIC_AUTH_PASSWORD = '_whatever0987!'  # leads to nowhere

    # correspondence plot
    BAR_WIDTH = 0.5
    OFFSET = 5

    URL_ESC = "#&&"

    # DB export
    PATH_DB_EXPORT = "Data/DB_export/"

    PATH_DB_ARCHIVE = "_archives.txt"
    PATH_DB_DOC_TYPES = "doc_types.txt"
    PATH_DB_DOCUMENT = "documents.txt"

    PATH_DB_FILES = "files.txt"
    PATH_DB_FILE_TYPES = "file_types.txt"
    PATH_DB_FILE_STATES = "file_states.txt"
    PATH_DB_FILE_LINKS = "file_links.txt"
    PATH_DB_DATES = "dates.txt"

    PATH_DB_PLACES = "loc_place.txt"
    PATH_DB_DISTRICTS = "loc_district.txt"
    PATH_DB_COUNTRIES = "loc_countries.txt"
    PATH_DB_COMPLEX_LOCATIONS = "loc_complex.txt"

    PATH_DB_TITLES = "corr_titles.txt"
    PATH_DB_COLLECTIVE = "corr_institutions.txt"
    PATH_DB_PERSONS = "corr_persons.txt"
    PATH_DB_PERSONS_INFO = "corr_persons_info.txt"
    PATH_DB_PERSONS_TITLES = "corr_persons_titles.txt"
    PATH_DB_ADD_TYPES = "corr_add_types.txt"
    PATH_DB_ADD_PERSONS = "corr_add_persons.txt"
    PATH_DB_ADD_TITLES = "corr_add_titles.txt"
    PATH_DB_ADD_INSTITUTIONS = "corr_add_institutions.txt"

    PATH_DB_LITERATURE = "doc_literature.txt"
    PATH_DB_PRINT = "doc_prints.txt"
    PATH_DB_BIBLIOGRAPHY = "_bibliography.txt"

    PATH_DB_DOC_LANG = "doc_language.txt"
    PATH_DB_SENTENCES = "doc_sentences.txt"
    PATH_DB_NOTES = "doc_notes.txt"
    PATH_DB_REMARK_TYPES = "_doc_note_types.txt"

    PATH_DB_LANGUAGE = "_languages.txt"
    PATH_DB_AUTHORIZATION = "_authorizations.txt"
    PATH_DB_USER = "_users.txt"
    PATH_DB_PAGE_VIEWS = "_page_views-u_id-url-t-1.txt"
    PATH_DB_PAGE_MODE = "_page_modes-i-mode.txt"

    FILE_STATES = [
        None,  # unbekannt
        "offen",
        "unklar",
        "ungültig",
        "abgeschlossen",
        "privat"
    ]

    ADD_TYPES = [
        None,
        "Privatperson",
        "Titulargruppe",
        "Institutionen",
    ]

    TITLES = [  # title, group
        [SN, SN],
        ["Abgeordneter", "Abgeordnete"],
        ["Adliger", "Adel"],
        ["Ältester", "Älteste"],
        ["Arzt", "Ärzte"],
        ["Astronom", "Astronomen"],
        ["Bischof", "Bischöfe"],
        ["Botschafter", "Botschafter"],
        ["Burger", "Burger"],
        ["Bürgermeister", "Bürgermeister"],
        ["Bruder", "Brüder"],
        ["Calvinist", "Calvinisten"],
        ["Christ", "Christen"],
        ["Dekan", "Dekane"],
        ["Doktor", "Doktoren"],
        ["Evangelikaner", "Evangelikaner"],
        ["Examinator", "Examinatoren"],
        ["Flüchtling", "Flüchtlinge"],
        ["Fürst", "Fürsten"],
        ["Geistlicher", "Geistliche"],
        ["Gelehrter", "Gelehrte"],
        ["Gesandther", "Gesandthe"],
        ["Gläubiger", "Gläubige"],
        ["Gnädiger Herr", "Gnädige Herren"],
        ["Graf", "Grafen"],
        ["Gräfin", "Gräfinnen"],
        ["Herr", "Herren"],
        ["Historiker", "Historiker"],
        ["Humanist", "Humanisten"],
        # ["Herzog", "Herzoge"],
        # ["Herzog", "Herzöge"],
        ["Jurist", "Juristen"],
        ["Kirchendiener", "Kirchendiener"],
        ["Kirchenleiter", "Kirchenleiter"],
        ["Kirchenrat", "Kirchenräte"],
        ["Kolloquent", "Kolloquenten"],
        ["König", "Könige"],
        ["Lehrer", "Lehrer"],
        ["Pastor", "Pastoren"],
        ["Mathematiker", "Mathematiker"],
        ["Meier", "Meier"],
        ["Pasteur", "Pasteurs"],
        ["Pfarrer", "Pfarrer"],
        ["Prediger", "Prediger"],
        ["Predikant", "Predikanten"],
        ["Prädikant", "Prädikanten"],
        ["Priester", "Priester"],
        ["Professor", "Professoren"],
        ["Propst", "Pröpste"],
        ["Protestant", "Protestanten"],
        ["Prädikant", "Prädikanten"],
        ["Päpstlicher Gesandter", "Päpstliche Gesandte"],
        ["Rat", "Räte"],
        ["Ratsherr", "Ratsherren"],
        ["Rechenherr", "Rechenherren"],
        ["Reformator", "Reformatoren"],
        ["Schulherr", "Schulherren"],
        ["Schulmeister", "Schulmeister"],
        ["Schultheiss", "Schultheissen"],
        ["Schulverordneter", "Schulverordnete"],
        ["Senior", "Senioren"],
        ["Syndic", "Syndics"],
        ["Staatsmann", "Staatsmänner"],
        ["Statthalter", "Statthalter"],
        ["Theologe", "Theologen"],
        ["Verfolgter Gläubiger", "Verfolgte Gläubige"],
        ["Verordneter Examinator", "Verordnete Examinatoren"],
        ["Verordneter", "Verordnete"],
        ["Vorsteher", "Vorsteher"]
    ]

    INSTITUTIONS = [
            [SN, SN],
            ["das Augsburger Bekenntnis", "die Augsburger Bekenntnisse"],
            ["Belgisch-Deutsche Fremdengemeinde", "Belgisch-Deutsche Fremdengemeinden"],
            ["Evangelische Gemeinde", "Evagelische Gemeinden"],
            ["Flüchtlingsgemeinde", "Flüchtlingsgemeinden"],
            ["Fremdengemeinde", "Fremdengemeinden"],
            ["Freiamt", "Freiämter"],
            ["Fremdkirche", "Fremdkirchen"],
            ["Fremdenkirche", "Fremdenkirchen"],
            ["Gemeinde", "Gemeinden"],
            ["Kapitel", "Kapitel"],
            ["Kapitel des Grossmünsterkapitels", "Kapitel der Grossmünster"],  # sic
            ["Kapitel des Grossmünsterstifts", "Kapitel der Grossmünsterstifte"],
            ["Kirche", "Kirchen"],
            ["La Compagnie des Pasteurs", "Les Compagnies des Pasteures"],
            ["Neue Zeitung", "Neue Zeitungen"],
            ["Polnisch-Litauischer Reichstag (Sejm)", "Polnisch-Litauische Reichstage (Sejm)"],
            ["Synode", "Synoden"],
            ["Ratskomission", "Ratskomissionen"],
            ["Reformierte Kirche", "Reformierte Kirchen"],
            ["Volk", "Völker"]
        ]

    COUNTRIES = [
        [SL],
        ["Albanien", "Albania", "Shqipëria"],
        ["Belgien", 'Belgium', 'België', 'Belgique', 'Belgien', 'België - Belgique - Belgien'],
        ["Brasilien", "Brasil"],
        ["Bulgarien", "Bulgaria", "Бългaрия"],
        ["China", "China 中国", "中国"],
        ["Deutschland", "Teutschland", "Germany"],
        ["Dänemark", "Denmark", "Danmark"],
        ["Elfenbeinküste", "Côte d'Ivoire"],
        ["England", "United Kingdom"],
        ["Frankreich", "France"],
        ["Italien", "Italy", "Italia"],
        ["Indien", "India"],
        ["Kroatien", "Croatia"],
        ["Litauen", "Lithuania", "Lietuva"],
        ["Maleisien", "Malaysia"],
        ["Niederlande", "Nederland", "Nederland", "Nederlân"],
        ["Österreich", "Austria"],
        ["Polen", "Poland", "Polska"],
        ["Rumänien", "Romania", "Rumania", "România"],
        ["Russland", "Russia", "Россия"],
        ["Schweiz", "Switzerland", "Suisse", "Svizzera", "Svizra", "Schweiz/Suisse/Svizzera/Svizra"],
        ["Siebenbürgen"],
        ["Slovenien", "Slovenia", "Slovensko"],
        ["Slowakei", "Slovakia"],
        ["Spanien", "Spain", "España"],
        ["Tschechien", "Czechia", "Czech Republic", "Česká republika"],
        ["Ungarn", "Hungary", "Magyarország"],
        ["USA", "United States of America"],
        ["Weißrussland", "Weissrussland", "Belarus", "Беларусь"]
    ]

    COMPLEX_LOCATIONS = [
        "die Städte der Eidgenossenschaft",
        "Welschland",
        "die drei Bünde",
        "die vier evangelischen Städte",
        "untere kurfürstliche Pfalz",
        "St. Germain/Poissy",
        "Solothurn oder Bern",
        "Rothenstein und Kalden",
        "Gyrsberg und Kempten",
        "Leslau / Włocławek",
        "Moldau/Rumänien",
        "Bergell und Veltlin",
        "Kopenhagen oder Kolding",
        "Moldau und Walachei",
    ]

    FILE_TYPES = [
        ["Neue Zeitung"],
        ["Begleitbrief", "Beibrief"],
        ["Brief"],
        ["Briefbeilage", "Beilage"],
        ["Hinweis"],
        ["keine Karteikarte", "Keine Karteikarte"],
        ["Postscriptum", "Nachschrift", "PS", "P.S.", "Nachtrag"],
        ["Rede", "Widmungsvorrede"],
        ["Rückseite"],
        ["Testament"],
        ["Verweis", "Verweiskarte"],
        ["Widmung"]
    ]

    LANGUAGES = [
        ["la", "de", "Latein"],
        ["de", "de", "Deutsch"],
        ["fr", "de", "Französisch"],
        ["en", "de", "Englisch"],
        ["it", "de", "Italienisch"],
        ["el", "de", "Griechisch"],
        ["de", "en", "German"],
        ["fr", "en", "French"],
        ["en", "en", "English"],
        ["it", "en", "Italian"],
        ["de", "fr", "Allemand"],
        ["fr", "fr", "Français"],
        ["en", "fr", "Angalis"],
        ["it", "fr", "Italien"],
        ["de", "it", "Tedesco"],
        ["fr", "it", "Francese"],
        ["en", "it", "Inglese"],
        ["it", "it", "italiano"],
    ]

    PLACES = [
        [SL],
        ["Aarau"],
        ["Aarburg"],
        ["Aarwangen"],
        ["Aeugst"],
        ["Allgäu"],
        ["Altdorf"],
        ["Altenklingen"],
        ["Altnau"],
        ["Altstätten"],
        ["Alzano Lombardo"],
        ["Amberg"],
        ["Anno"],
        ["Antorff"],
        ["Antwerpen"],
        ["Augsburg"],
        ["Auschwitz"],
        ["Backnang"],
        ["Baden", "Oberbaden", "Ober-Baden"],
        ["Baden-Baden"],
        ["Balgach"],
        ["Balingen"],
        ["Balzheim"],
        ["Basel"],
        ["Baxterley"],
        ["Bedford"],
        ["Belp"],
        ["Bem"],
        ["Berg"],
        ["Berg am Irchel"],
        ["Bergamo"],
        ["Bergell"],
        ["Berleburg", "Berlaburg"],
        ["Berlin"],
        ["Bern"],
        ["Bernang"],
        ["Bernhausen"],
        ["Betschwanden"],
        ["Biberach"],
        ["Biberstein"],
        ["Bichau"],
        ["Biecz"],
        ["Biel"],
        ["Bischofszell"],
        ["Bishopstorpe"],
        ["Blaubeuren"],
        ['Blumenthal'],
        ["Bocksberg"],
        ["Bologna"],
        ["Bonn"],
        ["Boppelsen"],
        ["Borssum"],
        ["Bourges"],
        ["Bradgate"],
        ["Bremen"],
        ["Bremgarten"],
        ["Breisach", "Breisach am Rhein"],
        ["Brescia"],
        ["Breslau"],
        ["Brest", "Brest-Litowsk"],
        ["Brugg"],
        ["Bubikon"],
        ["Buchs"],
        ["Burg Hohen-Aschau"],
        ["Burg Rheinfelden"],
        ["Burg Tarnow"],
        ["Burgund"],
        ["Burtenbach"],
        ["Buschhoven"],
        ["Bußnang"],
        ["Böblingen"],
        ["Böhmen"],
        ["Bülach"],
        ["Bünden"],
        ["Calcinato"],
        ["Calvidum"],
        ["Cambridge"],
        ["Casaccia"],
        ["Caspano"],
        ["Český"],
        ["Cham"],
        ["Chambéry"],
        ["Chavannes"],
        ["Chiavenna", "Ciavéna", "Cläven", "Cleven", "Kleven"],
        ["Chur"],
        ["Châtillon", "Châtillon-sur-Loing"],
        ["Colmar"],
        ["Compagnie"],
        ["Coventry"],
        ["Cremona"],
        ["Danzig", "Gdańsk", "Gduńsk"],
        ["Davos", "Tavate"],
        ["Debrezin"],
        ["Dießenhofen", "Diessenhofen"],
        ["Dieuze", "Duss", "Duß"],
        ["Domleschg"],
        ["Donauwörth"],
        ["Dover"],
        ["Dresden"],
        ["Dubiecko", "Dubiecz"],
        ["Duisburg"],
        ["Durham"],
        ["Dürnten"],
        ["Düsseldorf", "Regierungsbezirk Düsseldorf"],
        ["Eglisau"],
        ["Eibenschitz"],
        ["Eichstätt"],
        ["Elgg"],
        ["Elsass"],
        ["Ely"],
        ["Embrach"],
        ["Emden"],
        ["Entringen"],
        ["Eppingen"],
        ["Erbach"],
        ["Erfurt"],
        ["Erlenbach"],
        ["Esslingen"],
        ["Farnham Castle"],
        ["Fehraltorf"],
        ["Feiburg"],
        ["Feldlager"],
        ["Ferrara"],
        ["Fideris"],
        ["Fischingen"],
        ["Forstegg"],
        ["Franeker"],
        ["Frankenthal"],
        ["Frankfurt", "Frankfurt am Main"],
        ["Frauenfeld"],
        ["Freiburg"],
        ["Friedberg"],
        ["Friedewald"],
        ["Frzeslawicz"],
        ["Fulham"],
        ["Füssen"],
        ["Gachnang"],
        ["Genf"],
        ["Gent"],
        ["Gernersheim"],
        ["Gerzensee"],
        ["Giengen"],
        ["Gilford"],
        ["Girenbad"],
        ["Glarus"],
        ["Gloucester"],
        ["Gossau"],
        ["Graubünden"],
        ["Greenwich"],
        ["Grießenberg", "Grießenbergi", "Griessenberg", "Griesenberg"],
        ["Groningen"],
        ["Grönenbach"],
        ["Grüningen"],
        ["Guildford"],
        ["Gundelfingen", "Gundelfingen an der Donau"],
        ["Gunzenhausen"],
        ["Gyrenbad"],
        ["Gyrsberg"],
        ["Gyula"],
        ["Göppingen"],
        ["Görlitz"],
        ["Güttingen"],
        ["Hagenau"],
        ["Haldenstein"],
        ["Hall", "Hall in Tirol"],
        ["Hallwil"],
        ["Hamburg"],
        ["Handschuhsheim"],
        ["Hausen"],
        ["Hedelfingen"],
        ["Heideck"],
        ["Heidelberg"],
        ["Heiningen"],
        ["Herisau"],
        ["Hessen"],
        ["Hettingen"],
        ["Hinwil"],
        ["Hirzel"],
        ["Hohentwiel"],
        ["Holborn"],
        ["Homberg"],
        ["Hona"],
        ["Horburg"],
        ["Horgen"],
        ["Horn"],
        ["Hotteln"],
        ["Hunaweier"],
        ["Hundwil"],
        ["Höchstädt", "Höchstädt an der Donau"],
        ["Höngg"],
        ["Imola"],
        ["Ingolstadt"],
        ["Innsbruck"],
        ["Irchel"],
        ["Isny"],
        ["Iwanowicz", "Ivanowicz", "Iwanowicze"],
        ["Jenins"],
        ["Jonschwil"],
        ["Justingen"],
        ["Kalden"],
        ["Kappel am Albis", "Kappel"],
        ["Kassel"],
        ["Kaufbeuren"],
        ["Kempten"],
        ["Kilchberg"],
        ["Kirchberg"],
        ["Kleck"],
        ["Klettgau"],
        ["Kloten", "Rohr bei Kloten"],
        ["Köln", "Regierungsbezirk Köln"],
        ["Kolding"],
        ["Konstanz"],
        ["Kopenhagen"],
        ["Krafftheim"],
        ["Krakau"],
        ["Kronstadt"],
        ["Krumau"],
        ["Krumlov"],
        ["Krummenau"],
        ["Kuenshein"],
        ["Kyburg"],
        ["Köln"],
        ["Königsberg"],
        ["Königsfelden"],
        ["Küsnacht"],
        ["La Rochelles", "La Rochelle", "Rochelle", "Rochelles"],
        ["Lambeth"],
        ["Landshut"],
        ["Langenthal"],
        ["Laufen"],
        ["Lauingen"],
        ["Lausanne"],
        ["Lavin"],
        ["Leeder"],
        ["Leipzig"],
        ["Lenzburg"],
        ["Leslau"],
        ["Leutmerken"],
        ["Lichtenberg"],
        ["Lichtensteig"],
        ["Ligerz"],
        ["Lindau"],
        ["Litopolis"],
        ["Litowsk"],
        ["Locarno"],
        ["Lohrbach"],
        ["London", "London-Lambeth"],
        ["Lublin"],
        ["Ludham"],
        ["Luzern"],
        ["Lyon"],
        ["Lübeck"],
        ["Magdeburg"],
        ["Maggiatal"],
        ["Maienfeld"],
        ["Mailand"],
        ["Mainz"],
        ["Malans"],
        ["Manslacht"],
        ["Marbach"],
        ["Marburg"],
        ["Martiliasi"],
        ["Maschwanden"],
        ["Maulbronn"],
        ["Maur"],
        ["Meilen"],
        ["Melschtin"],
        ["Melsungen"],
        ["Memmingen"],
        ["Mesericz"],
        ["Metz"],
        ["Misox"],
        ["Mittelstetten"],
        ["Moers"],
        ["Moldau"],
        ["Montbéliard"],
        ["Montpellier"],
        ["Morbegno"],
        ["Morges"],
        ["Mosbach"],
        ["Mödingen"],
        ["Mömpelgard"],
        ["Mömpelgart"],
        ["Mülhausen"],
        ["München"],
        ["Neuburg", "Neuburg an der Donau"],
        ["Neuenburg"],
        ["Neumarkt"],
        ["Neunform", "Oberneunform", "Ober-Neunform", "(Ober-)Neunform"],
        ["Neunkirch"],
        ["Niederhone"],
        ["Niederurnen"],
        ["Niederweningen"],
        ["Norden"],
        ["Norwich"],
        ["Noyon", "Noviomagus Veromanduorum"],
        ["Nozereth"],
        ["Nozeroy"],
        ["Nyon"],
        ["Nîmes", "Nimes"],
        ["Nördlingen"],
        ["Nürnberg"],
        ["Oberglatt"],
        ["Oberlausitz"],
        ["Oldersum"],
        ["Oransko"],
        ["Orbe"],
        ["Orléans"],
        ["Orthius"],
        ["Osnabrück"],
        ["Osseko"],
        ["Osweczin"],
        ["Oswiecim"],
        ["Otelfingen"],
        ["Othmarsingen"],
        ["Ottenbach"],
        ["Oxford"],
        ["Padua"],
        ["Paris"],
        ["Payerne"],
        ["Pelsnica", "Pelsnicze"],
        ["Petrikau", "Piotrków"],
        ["Pewsum"],
        ["Pfalz"],
        ["Pforzheim"],
        ["Pfyn"],
        ["Pinczow"],
        ["Pinegow"],
        ["Plurs"],
        ["Poissy"],
        ["Polen"],
        ["Pontresina"],
        ["Posonium"],
        ["Promontogno"],
        ["Przeslawicz"],
        ["Puschlav"],
        ["Querceto"],
        ["Radziejow"],
        ["Rafz"],
        ["Ramsen"],
        ["Rappoltstein"],
        ["Rappoltsweiler", "Rappoldsweiler"],
        ["Rappoltweiler"],
        ["Rauschenberg"],
        ["Ravensburg"],
        ["Regensburg"],
        ["Reichenweier"],
        ["Reutlingen"],
        ["Rheinau"],
        ["Rheineck"],
        ["Rheinfelden"],
        ["Richmond"],
        ["Rickenbach"],
        ["Ringgen"],
        ["Roborst", "Borst", "Bost"],
        ["Rohr"],
        ["Rohrenfels"],
        ["Rolle"],
        ["Rom"],
        ["Romrath"],
        ["Rostock"],
        ["Roth"],
        ["Rothenstein"],
        ["Rottenstein"],
        ["Rottweil"],
        ["Ruremond"],
        ["Russikon"],
        ["Rötteln"],
        ["Rüti"],
        ["Saanen"],
        ["Sachsen"],
        ["Salisbury"],
        ["Samaden", "Samedan"],
        ["Schaffhausen"],
        ["Schafis"],
        ["Scharfenort"],
        ["Schattenhalb"],
        ["Scherzingen"],
        ["Scherzligen"],
        ["Schlachteck"],
        ["Schleiden"],
        ["Schlesien"],
        ["Schlettstadt", "Sélestat", "Sélestat", "Schlestadt"],
        ["Schleusingen"],
        ["Schopfheim"],
        ["Schramberg"],
        ["Schwanden"],
        ["Secomini"],
        ["Sem"],
        ["Sendomir"],
        ["Siebenbürgen"],
        ["Siena"],
        ["Sils im"],
        ["Sittaw"],
        ["Sitten"],
        ["Solangio"],
        ["Solothurn"],
        ["Sondrio"],
        ["Spangenberg"],
        ["Speier"],
        ["Speyer"],
        ["St.Gallen", "St. Gallen"],
        ["St.Germain", "St. Germain", "Saint-Germain", "St. Germain en Laye"],
        ["St.Margrethen", "St. Margrethen"],
        ["St.Peterzell", "St. Peterzell"],
        ["St.Poissy", "St. Poissy"],
        ["Stackboren"],
        ["Stammheim"],
        ["Steckborn"],
        ["Steeg"],
        ["Stein"],
        ["Stein am Rhein"],
        ["Straßburg", "Strassburg", "Strasbourg", "Schdroosburi"],
        ["Straubing"],
        ["Stuttgart"],
        ["Suhr"],
        ["Süs"],
        ["Tarnow"],
        ["Tegerfelden"],
        ["Thetford"],
        ["Thun"],
        ["Thüringen"],
        ["Tirano"],
        ["Tirol"],
        ["Toggenburg"],
        ["Tomice"],
        ["Torgau"],
        ["Töß"],
        ["Tübingen"],
        ["Ulm"],
        ["Urach"],
        ["Urdorf"],
        ["Uri"],
        ["Uster"],
        ["Veltheim"],
        ["Veltlin"],
        ["Vézelay"],
        ["Venedig"],
        ["Veringenstadt", "Veringendorf"],
        ["Vicosoprano"],
        ["Voras"],
        ["Vézelay"],
        ["Wagegg"],
        ["Walachei"],
        ["Walenstadt"],
        ["Waltenhofen"],
        ["Warschau"],
        ["Wartau"],
        ["Wasenberg"],
        ["Wattwil"],
        ["Wechingen"],
        ["Weinfelden"],
        ["Weinheim"],
        ["Wesel"],
        ["Westminster"],
        ["Wetter"],
        ["Wetzikon"],
        ["Wieliczka"],
        ["Wien"],
        ["Wiesendangen"],
        ["Wiesloch"],
        ["Wigoltingen"],
        ["Wildenberg"],
        ["Wilna"],
        ["Winchester"],
        ["Windsor"],
        ["Winterthur", "Oberwinterthur", "Ober-Winterthur"],
        ["Wittenberg"],
        ["Wlodislaw", "Wlodzislaw", "Wodzislaw", "Włocławek"],
        ["Wolfsheim"],
        ["Wolp"],
        ["Worcester"],
        ["Woringen"],
        ["Worms"],
        ["Wädenswil"],
        ["Wülflingen"],
        ["Württemberg"],
        ["Xions"],
        ["York"],
        ["Zagreb"],
        ["Zaliczin"],
        ["Zapfenburg"],
        ["Zator"],
        ["Ziegenhain"],
        ["Zittau"],
        ["Znaim"],
        ["Zofingen"],
        ["Zollikon"],
        ["Zug"],
        ["Zuoz"],
        ["Zurzach"],
        ["Zürich", "Züri", "Zurigo", "Turicum", "Zurich"],
        ["Neumarkt", "Zürich-Neumarkt"],
    ]

    DISTRICTS = [
        [[SL], [SL]],
        [["Aargau", "AG"], ["Schweiz"]],
        [['Aichach'], ['Deutschland']],
        [["Alföld és Észak", "Great Plain and North", "Grande Plaine et Nord"], ["Ungarn"]],
        [["Appenzell Ausserrhoden", "AR", "Appezell Osserode", "Appenzell Rhodes-Extérieures", "Appenzello Esterno", "Ausserrhoden", "Osserode", "Rhodes-Extérieures", "Esterno"], ["Schweiz"]],
        [["Baden-Württemberg"], ["Deutschland"]],
        [["Basel"], ["Schweiz"]],
        [["Baselland", "Basel-Landschaft", "Baselbiet", "BL"], ["Schweiz"]],
        [["Baselstadt", "Basel-Stadt", "Bâle-Ville", "Basilea Città"], ["Schweiz"]],
        [["Bayern"], ["Deutschland"]],
        [["Berlin"], ["Deutschland"]],
        [["Bern", "BE", "Berne", "Bern/Berne"], ["Schweiz"]],
        [["Bremen"], ["Deutschland"]],
        [["Brest", "Oblast Brest", "Breszkaja Woblasz", "Брестская область"], ["Weißrussland"]],
        [["Bretagne"], ["Frankreich"]],
        [["Burgund"], ["Frankreich"]],
        [["Elsass", "Elsaß", "Elsàss", "Elses", "Alsace"], ["Frankreich"]],
        [["Emilia-Romagna"], ["Italien"]],
        [["Flandern", "Vlaanderen"], ["Belgien"]],
        [["Friesland"], ["Niederlande"]],
        [["Genf", "GE", "Genève"], ["Schweiz"]],
        [["Glarus", "GL"], ["Schweiz"]],
        [["Graubünden", "GR", "Grigioni", "Grischun", "Graubünden/Grigioni/Grischun"], ["Schweiz"]],
        [["Groningen", "Gröningen", "Grönnen"], ["Niederlande"]],
        [["Großpolen", "Grosspolen", "Woiwodschaft Großpolen", "Woiwodschaft Großpolen", "województwo wielkopolskie"], ["Polen"]],
        [["Hamburg"], ["Deutschland"]],
        [["Hauptstadtregion", "Region Hovedstaden"], ["Dänemark"]],
        [["Hessen"], ["Deutschland"]],
        [["Jihovýchod"], ["Tschechien"]],
        [["Jihozápad"], ["Tschechien"]],
        [["Jędrzejowski", "Powiat Jędrzejowski", "powiat jędrzejowski"], ["Polen"]],
        [["Katalonien", "Cataluña", "Catalunya"], ["Spanien"]],
        [["Kleinpolen", "Woiwodschaft Kleinpolen", "województwo małopolskie", "Klein-Polen", "Polen (Klein-Polen)"], ["Polen"]],
        [["Kronstadt", "Brașov"], ["Rumänien"]],
        [["Kujawien-Pommern", "Woiwodschaft Kujawien-Pommern", "województwo kujawsko-pomorskie"], ["Polen"]],
        [["Latium", "Lazio"], ["Italien"]],
        [["Limburg", "Limburg an der Lahn", "Limburg a.d. Lahn"], ["Deutschland"]],
        [["Lombardei", "Lombardia", "Lumbardia"], ["Italien"]],
        [["Lothringen"], ["Frankreich"]],
        [["Lublin", "Woiwodschaft Lublin", "województwo lubelskie"], ["Polen"]],
        [["Luzern", "LU"], ["Schweiz"]],
        [["Mazovia", "Mazovian Voivodeship", "Mazovia Province", "województwo mazowieckie"], ["Polen"]],
        [["Mecklenburg-Vorpommern", "Mäkelborg-Vörpommern"], ["Deutschland"]],
        [["Metropolitanes Frankreich", "France métropolitaine", "la Métropole", "Metropolitan-Frankreich"], ["Frankreich"]],
        [["Mährisch-Schlesische Region", "Moravskoslezský kraj", "Moravskoslezsko"], ["Tschechien"]],
        [["Neuenburg", "Neuchâtel", "NE"], ["Schweiz"]],
        [["Niedersachsen"], ["Deutschland"]],
        [["Niederschlesien", "Woiwodschaft Niederschlesien", "województwo dolnośląskie"], ["Polen"]],
        [["Niederösterreich", "Ostarrîchi"], ["Österreich"]],
        [["Noord-Holland"], ["Niederlande"]],
        [["Nordrhein-Westfalen", "NRW"], ["Deutschland"]],
        [["Norfolk"], ["England"]],
        [["Nordwestrussland", "Föderationskreis Nordwestrussland", "Северо-Западный федеральный округ"], ["Russland"]],
        [["Oberdeutschland"], ["Deutschland"]],
        [["Oblast", "Woblasz", "Minskaja Woblasz", "Минская область", "Minskaja Oblast", "Минская область"], ["Weißrussland"]],
        [["Oise"], ["Frankreich"]],
        [["Ostfriesland", "Ost-Friesland"], ["Deutschland"]],
        [["Piemont", "Piemonte"], ["Italien"]],
        [["Pinneberg", "Pinnbarg"], ["Deutschland"]],
        [["Pińczowski", "Powiat Pińczowski", "powiat pińczowski"], ["Polen"]],
        [["Pommern", "Woiwodschaft Pommern", "województwo pomorskie"], ["Polen"]],
        [["Pressburger/Bratislavaer Landschaftsverband", "Bratislavský kraj"], ["Slowakei"]],
        [["Rheinland-Pfalz"], ["Deutschland"]],
        [["Sachsen"], ["Deutschland"]],
        [["Sachsen-Anhalt"], ["Deutschland"]],
        [["Salzburg"], ["Österreich"]],
        [["Schaffhausen", "SH"], ["Schweiz"]],
        [["Schleswig-Holstein"], ["Deutschland"]],
        [["Sélestat"], ["Frankreich"]],
        [["Severozápad"], ["Tschechien"]],
        [["Sibirien", "Föderationskreis Sibirien", "Сибирский федеральный округ"], ["Russland"]],
        [["Solothurn", "SO"], ["Schweiz"]],
        [["St. Gallen", "SG", "Sankt Gallen"], ["Schweiz"]],
        [["Středočeský", "Střední", "Středočeský kraj", "Střední Čechy"], ["Tschechien"]],
        [["Süddänemark", "Region Syddanmark"], ["Dänemark"]],
        [["Surrey"], ["England"]],
        [["Tessin", "Ticino"], ["Schweiz"]],
        [["Thurgau", "TG"], ["Schweiz"]],
        [["Thüringen"], ["Deutschland"]],
        [["Tirol"], ["Österreich"]],
        [["Toskana", "Toscana", "Etruria"], ["Italien"]],
        [["Uri", "UR", "Uronia", "Urania"], ["Schweiz"]],
        [["Venetien", "Venezien", "Veneto"], ["Italien"]],
        [["Waadt", "VD", "Vaud"], ["Schweiz"]],
        [["Wallis", "VS", "Valais", "Valais/Wallis"], ["Schweiz"]],
        [["Wien", "Vienna"], ["Österreich"]],
        [["Wilna", "Vilnius", "Vilniaus apskritis"], ["Litauen"]],
        [["Zagreb"], ["Kroatien"]],
        [["Zug", "ZG"], ["Schweiz"]],
        [["Zürich", "ZH"], ["Schweiz"]],
    ]

    PERSONS = [
        [[SN], [SN]],
        [['Abel'], ['Johannes', 'Johann', 'John', 'Hans']],
        [["Aberlin"], ["Joachim"]],
        [["Achatius"], ["Israelin"]],
        [['Acronius'], ['Phrysius Johannes', 'Frisius Johannes', 'Johannes', 'Frisius Johann', 'Phrysius Johann', 'Johann', 'Frisius John', 'Phrysius John', 'John']],
        [["Adlischwiler"], [SN]],
        [['Adlischwyler', 'Adelschwyler', 'Adlischwiler', 'Adelschwiler'], ['Johannes Jakob', 'Johannnes', 'Hans Jakob', 'Hans', 'Jakob', 'Johannes']],
        [['Adlischwyler', 'Adelschwyler', 'Adlischwiler', 'Adelschwiler'], ['Johannes', 'Johann', 'Johan', 'Hans']],
        [['Adlischwyler', 'Adelschwyler', 'Adlischwiler', 'Adelschwiler'], ['Margareta']],
        [["Agricola"], ["Joachim"]],
        [['Aichinger'], ['Christoph', 'Christophorus']],
        [["Aichler"], ["Michael"]],
        [["Albrecht"], ["Martin"]],
        [['Altieri'], ['Baldassare', 'Balthasar', 'Baldassar']],
        [['Anastasius', 'Versteghe', 'Veluanus'], ['Johannes', 'Jan Gerritszoon', 'Anastasius Johannes']],
        [["Amerbach"], ["Bonifacius"]],
        [["Ämisegger"], ["Konrad", "Conrad"]],
        [['Ampelander', 'Rebmann'], ['Valentin']],
        [["Anienus"], [SN]],
        [['Apriolus', 'Eberli', 'Eberlin'], ['Heinrich']],
        [["Arator"], ["Nikolaus"]],
        [["Arnauld"], ["Jean"]],
        [["Arnold"], ["Gabriel"]],
        [["Arnold"], ["Matthäus", "Mathäus"]],
        [["Avetius"], ["Benedikt"]],
        [["Aylmer"], ["John"]],
        [['a Belloloco', 'à Belloloco', 'de Beaulieu', 'Belloloco', 'Beaulieu'], ['Hektor', 'Eustorgius']],
        [['à Lasco', 'a Lasco', 'Lasitius', 'Lasicki', 'Lasicius', 'Laski'], ['Johannes', 'Johann', 'Jan', "Hans"]],
        [
            ["Bäldi"],
            ["Joachim"],
            "https://de.wikipedia.org/wiki/Joachim_B%C3%A4ldi",
            "/static/images/Portraits_Corr/Bäldi_Joachim.png"
        ],
        [["Bäldi"], ["Michael"]],
        [['Bachofen', 'Backofen'], ['Mathias', 'Matthias']],
        [["Badius"], ["Konrad", "Conrad"]],
        [["Banks"], ["John"]],
        [['Banc', 'Bancus'], ['Arnaud', 'Arnulphus']],
        [["Barberos"], ["Wilhelm"]],
        [['Barthelot', 'Barthelottus'], ['John', 'Johannes']],
        [['Baudouin', 'Bauduin', 'Balduinus'], ['François', 'Francois']],
        [['Beccaria'], ['Johannes', 'Giovanni']],
        [["Bechel"], ["Johannes"]],
        [['Bechlin'], ['Johannes', 'Johann']],
        [['Bechrer', 'Becherer', 'Becher'], ['Hans', 'Johann', 'Johannnes']],
        [['Beck', 'Becks', 'Beccius'], ['Dietrich', 'Theod. Laurentius']],
        [["Bellò"], ["Lucia"]],
        [["Bernher"], ["Augustin"]],
        [["Bérauld"], ["François"]],
        [['Bersius', 'Bertschi'], ['Marcus']],
        [['Bertlin', 'Berthlinus'], ['Bartholomäus', 'Bartholomaeus']],
        [['Besardus', 'Betschart'], ['Martin', 'Martinus']],
        [["Besozzo"], ["Antonio Mario", "Antonio"]],
        [["Beza"], [SN]],
        [
            ["Bibliander", "Buchmann"],
            ["Theodor"],
            "https://de.wikipedia.org/wiki/Theodor_Bibliander",
            "/static/images/Portraits_Corr/Bibliander_Theodor.jpg",
            [[SD, SD, 1505], ["Bischofszell", SL, SL, SL]],
            [[26, 9, 1564], ["Zürich", "Zürich", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Bindschedler"], ["Jakob", "Jacob"]],
        [["Bing"], ["Simon"]],
        [["Birk"], ["Emanuel"]],
        [['Birckmann', 'Birchmann', 'Birchman'], ['Johannes d.Ä.', 'Johannes der Ältere', 'Johann der Ältere', 'Hans der Ältere', 'Johann d.Ä.', 'Hans d.Ä.']],
        [['Birckmann', 'Birchmann', 'Birchman'], ['Johannes', 'Johann', 'Hans']],
        [["Bitter"], ["Dietrich"]],
        [
            ['Blarer', 'Blaurer', "Blarer von Giersberg", "Blaurer von Giersberg"],
            ['Ambrosius'],
            "https://de.wikipedia.org/wiki/Ambrosius_Blarer",
            "/static/images/Portraits_Corr/Blarer_Ambrosius.jpg",
            [[4, 4, 1492], ["Konstanz", SL, SL, SL]],
            [[6, 12, 1564], ["Winterthur", "Zürich", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [
            ["Blasius", "Bläsi"],
            ["Johannes", "Hans", "Johann"],
            "https://de.wikipedia.org/wiki/Johannes_Blasius",
            "",
            [[SD, SD, 1490], [SL, "Graubünden", "Schweiz", SL]],
            [[18, 7, 1550], ["Chur", "Graubünden", "Schweiz", SL]],
            ["Pfarrer", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
            ["Evangelikaner", [SD, SD, SD], [SD, SD, SD], [SL, "Schweiz", SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
        ],
        [["Blarer"], ["Diethelm"]],
        [["Blarer"], ["Jörg"]],
        [
            ["Blarer", "Blarer von Giersberg"],
            ["Thomas"],
            "https://de.wikipedia.org/wiki/Thomas_Blarer",
            "/static/images/Portraits_Corr/Blarer_Thomas.jpg",
            [[SD, SD, 1499], ["Konstanz", "Baden-Württemberg", "Deutschland", SL]],
            [[19, 3, 1567], [SL, SL, SL, SL]],
            ["Jurist", ["Neu-Giersberg", SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Blarer"], ["Thomas d.J.", "Thomas der Jüngere"]],
        [['Blasius', 'Blaise'], ['Marcuard']],
        [["Blaurer", "Blarer"], ["Augustin"]],
        [['Blum', 'Florus'], ['Johannes']],
        [["Bleuler"], ["Ulrich"]],
        [["Bluntschli"], ["Johannes", "Johann", "Hans"]],
        [
            ['de Bochetel', 'Bochetel', 'Bouchelet', 'Episcopus'],
            ['Bernardin', 'Rhedonenis'],
            'https://fr.wikipedia.org/wiki/Bernardin_Bochetel',
            '',
            [[SD, SD, SD, SL], [SL, SL, SL]],
            [[SD, SD, 1570], [SL, SL, SL, SL]],
            ['Prediger', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Geistlicher', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Bischof', [15, 1, 1561], [SD, SD, 1565], ['Rennes', 'Bretagne', "Frankreich", SL]],
            ['Botschafter', [SD, 2, 1554], [SD, 4, 1554], [SL, SL, "Schweiz"]],
            ['Botschafter', [SD, 10, 1554], [SD, SD, 1557], [SL, SL, "Schweiz"]],
            ['Botschafter', [SD, 1, 1558], [SD, SD, 1558], [SL, SL, "Schweiz"]]
        ],
        [["Boner"], ["Johannes", "Johann", "Hans"]],
        [['Bonett', 'Bellinchetti'], ['Franz']],
        [
            ["Borrhaus", "Cellarius", "Bürkß", "Borrhus"],
            ["Martin", "Martinus"],
            "https://de.wikipedia.org/wiki/Martin_Borrhaus",
            "",
            [[SD, SD, 1499], ["Stuttgart", SL, SL, SL]],
            [[11, 10, 1564], ["Basel", "Basel", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
            ["Professor", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
        ],
        [["Both"], ["Botus Cornelius", "Botus", "Cornelius"]],
        [["Boutin"], ["Jean"]],
        [['Bramburg', 'Bramburgius'], ['Paul', 'Pavel', 'Paulus']],
        [["Bramius"], ["Thomas"]],
        [["Brandmüller"], ["Johannes"]],
        [["Brenz"], ["Johannes"]],
        [["Breul"], ["Tilemann"]],
        [['Brunner', 'Fonteius', 'Fontejus'], ['Fridolin']],
        [["Brunner"], ["Johannes"]],
        [["Bucer"], ["Martin"]],
        [["Budé"], ["Jean"]],
        [["Bullinger", "Bullingerus"], ["Christoph"]],
        [["Bullinger", "Bullingerus"], ["Hans Rudolf", "Hans", "Rudolf", "Johann Rudolf", "Johannes Rudolf"]],
        [["Bullinger", "Bullingerus"], ["Heinrich d.J.", "Heinrich der Jüngere"]],
        [
            ["Bullinger", "Bullingerus"],
            ["Heinrich"],
            "https://de.wikipedia.org/wiki/Heinrich_Bullinger",
            "/static/images/Portraits_Corr/Bullinger_Heinrich.jpg",
            [[18, 7, 1504], ["Bremgarten", "Aargau", "Schweiz", SL]],
            [[17, 9, 1575], ["Zürich", "Zürich", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
            ["Protestant", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
        ],
        [["Bullinger", "Bullingerus"], ["Josua"]],
        [["Bullinger", "Bullingerus"], ["Rudolf"]],
        [["Bullinger", "Bullingerus"], [SN]],
        [["Burcher"], ["John"]],
        [["Butler"], ["John"]],
        [["Buzynski"], ["Hieronymus"]],
        [['Budny'], ['Simon', 'Szymon']],
        [
            ['Bullinger', "Bullingerus", 'Bullinger-Adlischwyler', 'Bullinger-Adlischwiler', 'Bullinger-Adelschwiler', 'Adlischwyler', 'Adlischwiler', 'Adelschwiler'],
            ['Anna'],
            "https://de.wikipedia.org/wiki/Anna_Bullinger",
            "/static/images/Portraits_Corr/Bullinger_Anna.jpg",
            [[SD, SD, 1505], ["Zürich", "Zürich", "Schweiz", SL]],
            [[17, 9, 1564], ["Zürich", "Zürich", "Schweiz", SL]],
        ],
        [['Bullinger', "Bullingerus"], ['Heinrich d.J.', 'Heinrich der Jüngere']],
        [['Bullinger', "Bullingerus"], ['Heinrich d.Ä.', 'Heinrich der Ältere']],
        [['Bullinger', "Bullingerus"], ['Johann', 'Johannes']],
        [['Butler'], ['Heinrich', 'Henry']],
        [["Caesarius"], ["Johannes"]],
        [["Calvin"], [SN]],
        [
            ["Calvin", "Calvinus", "Cauvin"],
            ["Johannes", "Ioannes", "Jehan", "Jean", "Johann", "Hans"],
            "https://de.wikipedia.org/wiki/Johannes_Calvin",
            "/static/images/Portraits_Corr/Calvin_Johannes.jpg",
            [[10, 7, 1509], ["Noyon", "Oise", "Frankreich", SL]],
            [[27, 5, 1564], ["Genf","Zürich", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Campell', 'Chiampell'], ['Ulrich', 'Durich', 'Duri', 'Durisch']],
        [['Campensis', 'Camph', 'ten Camph', 'von Kampen'], ['Petrus', 'Petrus Tom']],
        [['Caraccioli'], ['Galeazzo', 'Galeatius']],
        [["Cassander"], ["Georg"]],
        [["Chaillet"], ["David"]],
        [['Chytraeus', 'Chyträus'], ['David']],
        [["Cheke"], ["John"]],
        [["Chelmski"], ["Martian"]],
        [['Cirlerus', 'Zirler', 'Cirler'], ['Stephan', 'Steffanus']],
        [['Cleber', 'Kleber'], ['Eusebius', 'Euseb']],
        [
            ['Coignet', 'Cognet'],
            ['Matthieu', 'Matthaeus', 'Laberius', 'Martyn'],
            'https://en.wikipedia.org/wiki/Matthieu_Coignet',
            '',
            [[SD, SD, 1514], [SL, SL, SL, SL]],
            [[SD, SD, 1586], [SL, SL, SL, SL]],
            ["Jurist", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Botschafter", [SD, SD, SD], [SD, SD, 1562], [SL, SL, SL, SL]]
        ],
        [
            ['Coignet', 'Cognet'],
            ['Matthieu d.J.', 'Matthieu der Jüngere', 'Mattheus d.J.', 'Mattheus der Jüngere', 'Laberius, d.J.', 'Laberius der Jüngere', 'Martyn d.J.', "Martyn der Jüngere"]
        ],
        [
            ['Coignet', 'Cognet'],
            ['Matthieu d.Ä.', 'Matthieu der Ältere', 'Mattheus d.Ä.', 'Mattheus der Ältere', 'Laberius, d.Ä.', 'Laberius der Ältere', 'Martyn d.Ä.', "Martyn der Ältere"]
        ],
        [["Coignet-Rappoel"], ["Margrit"]],
        [['Collinus', 'Ambiel'], ['Caspar', 'Kaspar']],
        [["Collocutoribus"], [SN]],
        [
            ["Comander", "Dorfmann", "Hutmacher"],
            ["Johannes"],
            "https://de.wikipedia.org/wiki/Johannes_Comander",
            "",
            [[SD, SD, 1484], ["Maienfeld", "Graubünden", "Schweiz", SL]],
            [[SD, 1, 1557], ["Chur", "Graubünden", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
        ],
        [['Comes', 'Comte'], ['Beatus']],
        [['Cook', 'Cooke'], ['Anthony', 'Anthonius', 'Antony']],
        [['Cousin', 'Cognatus'], ['Gilbert', 'Gilbertus']],
        [["Coverdale"], ["Miles"]],
        [["Cox"], ["Richard"]],
        [["Craiß"], ["Johannes"]],
        [["Cranmer"], ["Thomas"]],
        [["Crapicensis"], ["Nicolaus Albertus", "Nicolaus", "Albertus"]],
        [['Crato', 'Crato von Krafftheim'], ['Johannes']],
        [['Crespin', 'Crispin', 'Crispinus'], ['Jean', 'Johannes', 'Johann', 'Johan', 'Hans']],
        [["Crispinus"], ["Leonhard"]],
        [["Crotus"], ["Hieronymus"]],
        [['Cruciger', 'Cruziger', 'Cruzinger', 'Krzyzak'], ['Felix']],
        [['Cruxceus', 'Crois', 'de la Croix', 'Cruxaeus', 'La Croix'], ['Nicolas']],
        [['Curio', 'Curione'], ['Coelius', 'Coelio', 'Caelio', 'Celio', 'Secundo', 'Secundus', 'Secondo', 'Coelius Secundo', 'Coelio Secundo', 'Caelio Secundo', 'Celio Secundo', 'Coelius Secundus', 'Coelio Secundus', 'Caelio Secundus', 'Celio Secundus', 'Coelius Secondo', 'Coelio Secondo', 'Caelio Secondo', 'Celio Secondo']],
        [["Czikowski"], ["Andres"]],
        [["Czikowski"], ["Stanislaus"]],
        [['Daius', 'Day'], ['Johannes', 'John']],
        [['Danmatter', 'Dammatter'], ['Christian']],
        [
            ['Dasypodius', "Hasenfratz", "Rauchfuß", "Rauchfuss"],
            ['Conrad', 'Konrad'],
            "https://de.wikipedia.org/wiki/Conrad_Dasypodius",
            "",
            [[SD, SD, SD], ["Frauenfeld", "Thurgau", "Schweiz", SL]],
            [[SD, 4, 1600], ["Straßburg", "Elsass", "Schweiz", SL]],
            ["Mathematiker", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Astronom", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [
            ["Dasypodius"],
            ["Petrus"],
            "https://de.wikipedia.org/wiki/Petrus_Dasypodius",
            "/static/images/Portraits_Corr/Dasypodius_Petrus.jpg"
        ],
        [['Dathenus'], ['Petrus', 'Peter']],
        [['De La Borde', 'Bordesius'], ['Jacques', 'Jacobus']],
        [['Del Corro', 'Corranus'], ['Antonio', 'Antonius']],
        [['Delescourre', 'Scorranus'], ['Jean', 'Johannes']],
        [['Della Rovere', 'von Mailand', 'Della Rovere da Milano', 'Milanese'], ['Giulio', 'Julius']],
        [['Desouches', 'Disonthes'], ['Léodegar', 'Leodigarius']],
        [['Despota', 'Despotul', 'Fürst Moldau und Walachei'], ['Jacoubs Heraclides', 'Jacob Eraclide']],
        [["Dipelius"], ["Nikolaus"]],
        [['Dluski', 'Dluska', 'Dluska-Kottwitz', 'Dluski-Kottwitz'], ['Agnes']],
        [['Dluski', 'Dluska', 'Dluska-Kottwitz', 'Dluski-Kottwitz'], ['Nikolaus']],
        [["Dryander"], ["Franciscus"]],
        [["Dryander"], ["Johannes"]],
        [['Dürnhofer'], ['Lorenz', 'Laurenz', 'Laurentius', 'Laurent']],
        [["Dudith"], ["Andreas"]],
        [['Dumont', 'Montanus'], ['Luc', 'Lucas']],
        [['Duno', 'Dunus'], ['Taddeo', 'Thaddaeus']],
        [["de Bellièvre", 'de Bellievre', 'Bellièvre', 'Bellievre'], ["Pomponne"]],
        [['de Bellièvre', 'de Bellievre', 'Bellièvre', 'Bellievre', 'sieur de Hautefort'], ['Jean']],
        [
            ['de Bèze', 'von Beza', 'Bèze', 'Beza', 'Beze', 'Besze'],
            ['Théodor', 'Théodore', 'Theodor', 'Theodore'],
            "https://de.wikipedia.org/wiki/Th%C3%A9odore_de_B%C3%A8ze",
            "/static/images/Portraits_Corr/Beza_Theodor.jpg",
            [[24, 6, 1519], ["Vézelay", "Burgund", "Frankreich", SL]],
            [[13, 10, 1605], ["Genf", "Genf", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
    ],
        [['de Bourbon', 'Bourbon', 'de Condé', 'Condé'], ['Antoine']],
        [['de Bourbon', 'Bourbon'], ['Henry', 'Henri']],
        [['de Bourbon', 'Bourbon'], ['Louis', 'Louis Ier', 'Loius Ier']],
        [["de Cambray"], ["Jean Jacques", "Jean", "Jacques"]],
        [["de Carraria"], ["Hieronymus"]],
        [['de Coligny', 'Chastillon'], ['Gaspard']],
        [['de Cougnée', 'de Cougnées', 'Le Vasseur', 'Cougnées', 'Vasseur'], ['Antoine', 'Jacques']],
        [["de Ferrières"], ["Jean"]],
        [["de Grantrye"], ["Pierre", "Peter", "Petrus"]],
        [['de Jonvilliers', 'Jonvilliers', 'Jonvillaeus'], ['Charles', 'Carolus']],
        [['de l\'Aubespine', 'de l’Aubespine'], ['Sébastien', 'Sebastian']],
        [['de Museau', 'Musaeus', "Museau"], ['Antoine Morelet', 'Maurus', 'Mauritius']],
        [['de Poix Séchelles', 'sieur de Séchelles', 'Poix Séchelles', "Poix"], ['Jean']],
        [["de Ugonibus"], ["Johannes Andreas", "Johannes", "Andreas", "Johann", "Hans"]],
        [["della Rovere da Milano", "della Rovere", "Rovere"], ["Giulio"]],
        [['des Gallars', 'Des Gallars', 'Gallatius', 'Gallars', 'Gallasius'], ['Nikolaus', 'Nicolas']],
        [["du Fraisse"], ["Jean"]],
        [["du Moulin", "Moulin"], ["Charles"]],
        [['du Moulin', 'Du Moulin', 'Molinius'], ['Claude', 'Claudius']],
        [["Ebel"], ["Heinrich"]],
        [["Eggelius"], ["Karl"]],
        [
            ['Egli', 'Iconius'],
            ['Tobias'],
            "https://de.wikipedia.org/wiki/Tobias_Egli",
            "",
            [[SD, SD, 1524], ["Zürich", "Zürich", "Schweiz", SL]],
            [[15, 11, 1574], ["Chur", "Graubünden", "Schweiz", SL]],
            ["Pfarrer", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Evangelikaner", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Ehem'], ['Christoph', 'Christopherus', 'Christophorus']],
        [["Ehinger"], ["Johannes"]],
        [["Enoc"], ["Louis"]],
        [
            ['Erastus', 'Erast', "Lüber", "Liebler"],
            ['Thomas'],
            "https://de.wikipedia.org/wiki/Thomas_Erastus",
            "/static/images/Portraits_Corr/Erastus_Thomas.jpg",
            [[7, 9, 1524], ["Baden", "Aargau", "Schweiz", SL]],
            [[31, 12, 1583], ["Basel", "Basel", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Professor", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Arzt", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [
            ['Erb'],
            ['Matthias', 'Mathias'],
            "https://de.wikipedia.org/wiki/Matthias_Erb",
            "",
            [[SD, SD, 1494], [SL, SL, SL, SL]],
            [[13, 3, 1571], ["Rappoltsweiler", SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Erni"], ["Lienhart"]],
        [["Escher"], ["Konrad"]],
        [['Ewich'], ['Johannes', 'Johann']],
        [["Fäsi"], ["Oswald"]],
        [['Fabri', 'Faber', 'Libertet'], ['Christophe', 'Christoph']],
        [["Fabricius"], ["Heinrich"]],
        [
            ["Fabricius Montanus", "Fabricius", "Montanus", "Schmid"],
            ["Johannes", "Johann", "Hans", "Jean"],
            "https://de.wikipedia.org/wiki/Johannes_Fabricius_Montanus",
            "",
            [[SD, SD, 1527], ["Bergheim", "Elsass", "Frankreich", SL]],
            [[5, 9, 1566], ["Chur", "Graubünden", "Schweiz", SL]],
        ],
        [["Fabricius"], [SN]],
        [['Fabricius', 'Düsseldorpianus', 'Orion', 'Faber'], ['Karl', 'Carolus', 'Janus', 'Engelbert']],
        [['Falais', 'Falesius', 'von Burgund', 'de Bourgogne', 'Burgundia'], ['Jakob', 'Jacques']],
        [["Farel"], ["Wilhelm"]],
        [["Farnowski"], ["Stanislaus"]],
        [['Fehr', 'Fer'], ['Jakob']],
        [['Fejérthóy', 'Feyerthoy', 'Fejérthoy', 'Fejértóy'], ['Johannes', 'János']],
        [["Festenberger"], ["Georg"]],
        [['Finck'], ['Konrad', 'Conrad']],
        [['Finsler', 'Vinslerus'], ['Josua', 'Josias']],
        [['Foxe'], ['John', 'Johannes']],
        [["Francis"], ["Russel"]],
        [['Franciscus', 'Francisco', 'Franz'], ['Dryander', 'Dryander de Enzinas']],
        [["Fratribus"], [SN]],
        [['Frei', 'Freigius'], ['Johann Thomas', 'Thomas', 'Johann']],
        [["Frensham"], ["Edward"]],
        [['Frey', 'Frei', 'Liberius', 'Liévin', 'Sr de Beaulieu'], ['Johann Leopold', 'Johann', 'Leopold', 'Johannes', 'Jean']],
        [
            ["Fries", "Frisius"],
            ["Johannes"],
            "https://de.wikipedia.org/wiki/Johannes_Fries",
            "/static/images/Portraits_Corr/Fries_Johannes.jpg",
            [[SD, SD, 1505], ["Greifensee", "Zürich", "Schweiz", SL]],
            [[28, 1, 1565], ["Zürich", "Zürich", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Lehrer", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Frisching"], ["Christiana"]],
        [["Frisching"], ["Theobald"]],
        [
            ['Frölich', 'Froelich', 'Laetus', "Lätus", "Letus"],
            ['Georg'],
            "https://www.deutsche-biographie.de/sfz17760.html",
            ""
        ],
        [["Frobenius"], ["Hieronymus"]],
        [["Froschauer"], ["Christoph d.J.", "Christoph der Jüngere"]],
        [["Fünkli"], ["Jakob"]],
        [["Fürst"], [SN]],
        [['Funck', 'Funk', 'Funccius', 'Fedmiger'], ['Johannes', 'Johan', 'Johann']],
        [["Furtmüller"], ["Hans Valentin", "Hans", "Valentin"]],
        [['Gadius', 'Gaddi'], ['Paulus']],
        [
            ["Gallicius", "Saluz"],
            ["Philipp"],
            "https://de.wikipedia.org/wiki/Philipp_Gallicius",
            "",
            [[4, 2, 1504], [SL, SL, SL, SL]],
            [[7, 7, 1566], ["Chur", SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Gardirius"], ["Geldrus Gerhardus", "Geldrus", "Gerhardus"]],
        [['Garnerius', 'Garnier'], ['Johannes', 'Jean']],
        [["Gasser"], ["Achilles Pirmin", "Achilles", "Pirmin"]],
        [
            ["Gast", "Peregrinus"],
            ["Johannes"],
            "https://de.wikipedia.org/wiki/Johannes_Gast",
            "",
            [[SD, SD, 1500], ["Breisach am Rhein", "Baden-Württemberg", "Deutschland", SL]],
            [[26, 7, 1552], ["Basel", "Basel", "Schweiz", SL]],
            ["Geistlicher", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Evangelikaner", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Georg'], ['Mönhart', 'Monnhart']],
        [["Gerlach"], ["Jörg"]],
        [['Geßner', 'Gessner', 'Gesner'], ['Konrad', 'Conrad']],
        [['Gilowski', 'Gilovius'], ['Pawel', 'Paul', 'Paulus']],
        [['Gimper', 'Gymper'], ['Kaspar']],
        [["Giowski"], ["Pawel"]],
        [["Gleim"], ["Otto"]],
        [["Grübel"], ["Sebastian"]],
        [["Gracilis"], ["St."]],
        [["Grais"], ["Johann"]],
        [['Grasser', 'Grasserus'], ['Jonas']],
        [['Grataroli', 'Gratarolus'], ['Wilhelm', 'Guglielmo', 'Guilhelmus', 'Gulielmus']],
        [['Gray', 'Grey'], ['Henry']],
        [['Gray', 'Grey'], ['Jane', 'Jana']],
        [["Gremp"], ["Ludwig"]],
        [["Grindal"], ["Edmund"]],
        [
            ["Grynaeus"],
            ["Johannes Jakob", "Johann Jakob", "Hans Jakob", "Johannes Jacob", "Johann Jacob", "Hans Jacob", "Johannes Jakobus", "Johann Jakobus", "Hans Jakobus", "Johannes Jacobus", "Johann Jacobus", "Hans Jacobus", "Johannes Iacobus", "Johann Iacobus", "Hans Icobus", "Johannes", "Johann", "Hans", "Jakob", "Jacob", "Jakobus", "Jacobus", "Iacobus"],
            "https://de.wikipedia.org/wiki/Johann_Jakob_Grynaeus",
            "/static/images/Portraits_Corr/Grynaeus_Johannes.jpg",
            [[1, 10, 1540], ["Bern", "Bern", "Schweiz", SL]],
            [[30, 8, 1617], ["Basel", "Basel", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], ["Basel", "Basel", "Schweiz", SL]],
        ],
        [
            ["Grynaeus", "Grynäus", "Griner"],
            ["Simon", "Simon d.J.", "Simon der Jüngere"],
            "https://de.wikipedia.org/wiki/Simon_Grynaeus",
            "/static/images/Portraits_Corr/Grynaeus_Simon.jpg",
            [[SD, SD, 1493], ["Veringendorf", "Baden-Württemberg", "Deutschland", SL]],
            [[1, 8, 1541], ["Basel", "Basel", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Guanget', 'Guangetus'], ['Delphinat']],
        [["Guarinono"], ["Thomaso"]],
        [["Gügeli"], ["Johannes", "Johann", "Hans"]],
        [["Gwalther"], [SN]],
        [
            ["Gwalther"],
            ["Rudolf"],
            "https://de.wikipedia.org/wiki/Rudolf_Gwalther",
            "/static/images/Portraits_Corr/Gwalther_Rudolf.jpg",
            [[2, 10, 1519], ["Zürich", "Zürich", "Schweiz", SL]],
            [[25, 12, 1586], ["Zürich", "Zürich", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [
            ["Gwalther"],
            ["Rudolf d.J.", "Rudolf der Jüngere"]
        ],
        [['Haab', 'Hab'], ['Johannes']],
        [["Hack"], ["Peter"]],
        [["Haddon"], ["James"]],
        [["Hagenberg"], ["Hans Rudolf", "Hans", "Rudolf", "Johann", "Johannes"]],
        [["Hales"], ["Christopher"]],
        [["Haller"], [SN]],
        [['Haller'], ['Johannes Jakob', 'Johann Jakob', 'Johannes', "Jakob"]],
        [["Haller"], ["Sulpicius"]],
        [['Haller'], ['Wolfgang', 'Wolf']],
        [["Hamberger"], ["Hartmann"]],
        [['Happel', 'Happelius'], ['Wigand']],
        [["Hardenberg"], ["Albert"]],
        [['Hardesheim', 'Herdesianus', 'Herdessianus'], ['Christoph']],
        [["Harding"], ["Thomas"]],
        [['Hartung'], ['Johannes', 'Johann', "Hans"]],
        [["Haug"], ["David"]],
        [['Hauser', 'Hauss'], ['Joseph']],
        [["Hägeli"], ["Johannes"]],
        [["Hedinger"], ["Heinrich"]],
        [["Hedio"], ["Euseb"]],
        [["Hedio"], ["Kaspar"]],
        [["Hegner"], ["Diethelm"]],
        [["Heim"], ["Lucius"]],
        [["Herdenius"], ["Helfrich"]],
        [["Hermann"], ["Daniel"]],
        [["Herold"], ["Johannes"]],
        [['Herold'], ['Michael', 'Michel']],
        [["Herrman"], ["Rudolf"]],
        [["Herter"], ["Joachim"]],
        [["Herter"], ["Johannes"]],
        [["Herterus"], ["Johannes"]],
        [["Herzog von Guise", "von Guise"], [SN]],
        [["Herzog von Württemberg", "von Württemberg"], ["Christoph"]],
        [["Heyden"], ["Johannes"]],
        [["Hilles"], ["Richard"]],
        [["Hirsgarter"], ["Matthias"]],
        [["Ho"], ["Leonhard"]],
        [["Hochholzer"], ["Christian"]],
        [["Hoffhalter"], ["Katharina"]],
        [["Hoffmann"], ["Marcus"]],
        [["Holdermeyer"], ["Jost"]],
        [["Hollerius"], ["Blasius"]],
        [['Holzwart'], ['Mathias', 'Matthias']],
        [['Hooper', 'Hopper'], ['John']],
        [['Hooper'], ['Anne', 'Anna']],
        [['Horn', 'Horne'], ['Robert']],
        [["Hortinus"], ["Michael"]],
        [["Hoser"], ["David"]],
        [["Hoser"], ["Simprecht"]],
        [["Hospinian", 'Hospinianus'], ["Christian"]],
        [
            ['Hospinian', 'Hospinianus', 'Wirt', 'Wirth', 'Steinanus'],
            ['Johannes', 'Johann', 'Hans'],
            "https://de.wikipedia.org/wiki/Johannes_Hospinianus",
            "",
            [[SD, SD, 1515], ["Stein am Rhein", "Schaffhausen", "Schweiz", SL]],
            [[SD, SD, SD], [SL, SL, SL, SL]],
            ['Professor', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [
            ['Hotman', 'Hotmann', "Hotomanus", 'Hotomann', 'Hotomannus', "Hottomannus", "Seigneur de Villiers-Saint-Pol"],
            ['François', 'Francois', 'Franz', 'Franziskus', 'Franciscus', 'Franziscus'],
            "https://de.wikipedia.org/wiki/Franciscus_Hotomanus",
            "/static/images/Portraits_Corr/Hotman_Francois.jpg",
            [[23, 8, 1524], ["Paris", "Paris", "Frankreich", SL]],
            [[12, 2, 1590], ["Basel", "Basel", "Schweiz", SL]],
            ["Calvinist", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Protestant", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Hüsseli"], ["Kaspar", "Caspar"]],
        [["Hürus"], ["Hieronymus"]],
        [["Hüsli"], ["Rudolf"]],
        [['Hubenschmid'], ['Kaspar', 'Caspar']],
        [['Hubert', 'Huprecht'], ['Konrad', 'Conrad']],
        [['Hug', 'Hugo', 'Hug(o)'], ['Johannes d.J.', 'Johannes der Jüngere']],
        [
            ['Hug', 'Hugo', "Hugonis", 'Hug(o)'],
            ['Johannes', 'Johann', 'Johannes II.'],
            "https://de.wikipedia.org/wiki/Johannes_Hug",
            "",
            [[SD, SD, 1455], ["Schlettstadt", SL, SL, SL]],
            [[SD, SD, 1505], ["Straßburg", SL, SL, SL]],
            ["Geistlicher", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Humphrey'], ['John Laurence', 'Laurence']],
        [['Hussar', 'Huszár'], ['Gallus', 'Gál']],
        [['Hyperius', 'Gheeraerdts'], ['Laurentius']],
        [["Hyperius"], ["Andreas"]],
        [["Israel"], ["Georg"]],
        [["im Thurn", "Thurn"], ["Hans", "Johannes", "Johann"]],
        [['Jaske', 'Jaskeus'], ['Johannes', "Johann", "Hans"]],
        [['Jeger', 'Jegerus', 'Jäger', 'Jägerus'], ['Isaak', 'Isaac', 'Jsaak']],
        [["Jenisch"], ["Marx"]],
        [["Jewel"], ["John"]],
        [["Jociscus"], ["Andreas"]],
        [["Jordan"], ["Spithek"]],
        [["Jung"], ["Johannes", "Johann", "Hans"]],
        [["K."], ["Jacob", "Jakob"]],
        [["Kambli"], ["Johannes", "Johann", "Hans"]],
        [["Kappeler"], ["Veit"]],
        [["Karli"], ["Gregor", "Gregorius"]],
        [["Karlin"], ["Gregor", "Gregorius"]],
        [['Kaufmann', 'Emporus'], ['Hieronymus']],
        [['Keller', 'Cellarius'], ['Georg', 'Josua']],
        [["Keller"], ["Diethelm"]],
        [["Keller"], ["Hans", "Johannes", "Johann"]],
        [["Kerez"], ["Jakob", "Jacob"]],
        [
            ['Kessler', "Ahenarius"],
            ['Johannes', 'Josua', "Johann", "Hans"],
            "https://de.wikipedia.org/wiki/Johannes_Kessler_(Theologe)",
            "",
            [[SD, SD, 1502], ["St. Gallen", SL, SL, SL]],
            [[7, 2, 1574], ["St. Gallen", SL, SL, SL]],
            ['Theologe', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Reformator', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Kessler"], ["Samuel"]],
        [["Kielmann"], ["Johannes", "Johann", "Hans"]],
        [["Kilchmeier"], ["Jodocus"]],
        [
            ["Kilchmeyer"],
            ["Jodocus", "Jost"],
            "https://de.wikipedia.org/wiki/Jodocus_Kilchmeyer",
            "/static/images/Portraits_Corr/Kilchmeyer_Jodocus.jpg",
            [[SD, SD, 1490], ["Bern", "Bern", "Schweiz", SL]],
            [[SD, SD, 1552], ["Bern", "Bern", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Kiszka'], ['Johannes', 'Jan', "Johann", "Hans"]],
        [["Klauser"], ["Konrad"]],
        [["Klebitz"], ["Wilhelm"]],
        [['Klösel', 'Khlesl'], ['Anton', "Antonius"]],
        [["Knibb"], ["Paul"]],
        [['Knip', 'Cnipius'], ['Johannes', "Johann", "Hans"]],
        [["Knox"], ["John"]],
        [['König von Polen', 'König'], ['Sigismund II. August', 'Zygmunt II.', 'Sigismund II.', 'Sigismund', 'Zygmunt', 'August']],
        [['König', 'Regius'], ['Nikolaus']],
        [["Kolb"], ["Andreas"]],
        [['Kranz', 'Sertorius'], ['Hieronymus']],
        [['Krowicki', 'Crovitius'], ['Martin', "Martinus"]],
        [["Krug"], ["Kaspar"]],
        [["Krupek"], ["Konrad"]],
        [["Kugelmann"], ["Georg"]],
        [['Kunheim', 'Kunhaim', 'Künhaim', 'von Kunheim', 'von Kunhaim', 'von Künhaim'], ['Erhard']],
        [["La Croix"], [SN]],
        [["Laetus"], ["Erasmus"]],
        [['Landgraf von Hessen', 'von Hessen'], ['Philipp']],
        [['Landgraf von Hessen', 'von Hessen'], ['Wilhelm', 'Wilhelm IV.']],
        [["Landgraf von Sulz"], ["Wilhelm"]],
        [["Languet"], ["Hubert"]],
        [["Lavater"], ["Ludwig"]],
        [["Le Gras"], ["Robert"]],
        [['Le Machon', 'Lematzotz'], [SN]],
        [["Lehwald"], ["Balthasar"]],
        [['Leith', 'Lecheus'], ['James', 'Jacobus Anglus']],
        [["Lening"], ["Johannes", "Johann", "Hans"]],
        [['Lentulo', 'Lentulus'], ['Scipio', 'Scipione']],
        [["Lever"], ["Thomas", "Tom"]],
        [["Leymer"], ["Thomas", "Tom"]],
        [["Lindauer"], ["Bernhard", "Bernard", "Bernardo"]],
        [["Liner"], ["Hans", "Johann", "Johannes"]],
        [['Linggi', 'Levinus', 'Linki', 'Laevinus'], ['Heinrich']],
        [['Lismaninus', 'Lismanninus', 'Lismanini', 'Lismanino'], ['Franciscus', 'Francesco', 'Franz']],
        [["Löwenklau"], ["Johannes", "Johann", "Hans"]],
        [['Lochmann'], ['Hans Heinrich', 'Heinrich']],
        [["Londanus"], ["Ricaudus"]],
        [['Loyseau', 'Loysamme'], ['O.']],
        [['Lusinski', 'Lusenius'], ['Johannes', "Johann", "Hans"]],
        [["Lyb"], ["Jakob", "Jacob"]],
        [["Lycosthenes"], ["Konrad", "Conrad"]],
        [
            ['Lydius'],
            ['Martin', 'Martinus'],
            "https://de.wikipedia.org/wiki/Martin_Lydius",
            "",
            [[SD, SD, 1539], ["Lübeck", "Schleswig-Holstein", "Deutschland", SL]],
            [[27, 7, 1601], ["Franeker", "Friesland", "Niederlande", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Professor", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Märtyrer"], [SN]],
        [["Mader"], ["Balthasar"]],
        [['Magius', 'Maggi'], ['Vincentius', 'Vincenzo']],
        [["Maier", "Meyer"], ["Nikolaus", "Nicolaus"]],
        [['Mainardi', 'Mainard', 'Mainardo', 'Mainardus'], ['Agostino', 'Augustin', 'Augustinus']],
        [['Maler', 'Pictorius'], ['Josua']],
        [["Maler"], ["Michael"]],
        [["Mameranus"], ["Nikolaus"]],
        [['Marcuard'], ['Blaise', 'Blasius']],
        [["Marti"], ["Ambrosius"]],
        [['Marti', 'Aretius'], ['Benedikt']],
        [['Martinengo', 'Martinenghi', 'Martinengus'], ['Celso', 'Celsus']],
        [['Martinengo', 'Martinengus', 'Martinenghi'], ['Ulysse', 'Ulysses', 'Ulisse', 'Ulisses']],
        [['Massarius', 'Massurius'], ['Hieronymus']],
        [['Matthäus', 'Matthaeus'], ['Johannes Heinrich', 'Johannes', 'Heinrich']],
        [['Matthäus', "Matthaeus"], ["Johannes", "Johann", "Hans"]],
        [["Maximilian II"], [SN]],
        [['May'], ['Claudius', 'Glado']],
        [["Meier"], [SN]],
        [["Melanchthon"], ["Philipp"]],
        [["Melanchthon"], [SN]],
        [["Melander"], ["Dionysius d.J.", "Dionysius der Jüngere"]],
        [["Melius"], ["Peter", "Petrus"]],
        [["Menius"], ["Eusebius"]],
        [['Menscheverus', 'Menschever', 'Menscheverus Frisius Groningensis'], ['Heinrich', 'Henricus']],
        [['Meyer', 'Agricola'], ['Lorenz', 'Laurentius', 'Laurenz']],
        [["Meyer"], ["Rudolf"]],
        [["Micronius"], ["Martin", "Martinus"]],
        [['Milander', 'Eppelmann'], ['Engelbert']],
        [['Mommer', 'Mommerus'], ['Ägidius', 'Aegidius']],
        [["Monau"], ["Jakob", "Jacob"]],
        [["Monier"], ["Claude"]],
        [['Mont', 'Montius', 'Mundt'], ['Christoph', 'Christopher', 'Christopherus', 'Christophorus']],
        [["Montmeiamus"], ["B."]],
        [['Moranges', 'Morangius'], ['Guy']],
        [["Morelet de Museau"], [SN]],
        [["Morison"], ["Richard"]],
        [['Mortius', 'de Niort'], ['Detus', 'Odet']],
        [["Multavius"], ["Joachim"]],
        [["Mumius"], ["Tilemanus"]],
        [["Murer"], ["Johann Jakob"]],
        [["Musculus", "Muskulus"], ["Abraham"]],
        [["Musculus", "Muskulus"], ["Johann Heinrich", "Johann", "Heinrich", "Johannes Heinrich", "Hans"]],
        [
            ["Musculus", "Muskulus", "Müslin", "Mäuslin", "Mäuslein"],
            ["Wolfgang"],
            'https://de.wikipedia.org/wiki/Wolfgang_Musculus',
            '/static/images/Portraits_Corr/Wolfgang_Musculus_(Herzog).png',
            [[8, 9, 1497], ['Dieuze', 'Lothringen', 'Frankreich', SL]],
            [[30, 8, 1563], [SN, 'Bern', 'Schweiz', SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [
            ["Myconius"],
            ["Oswald"],
            "https://de.wikipedia.org/wiki/Oswald_Myconius",
            "/static/images/Portraits_Corr/Myconius_Oswald.jpg",
            [[SD, SD, 1488], ["Luzern", "Luzern", "Schweiz", SL]],
            [[14, 10, 1552], ["Basel", "Basel", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Schweiz", SL]],
        ],
        [["Mylius"], ["Jeremias"]],
        [["Mönhart"], ["Georg"]],
        [["Mötteli"], ["Martin", "Martinus"]],
        [['Müller'], ['Georg Jörg', 'Georg', 'Jörg']],
        [["Müller"], ["Johann Baptist", "Johann", "Baptist"]],
        [["Müller"], ["Kaspar", "Caspar"]],
        [['Müsch', 'Müschius'], ['Johannes']],
        [['Myszkowski', 'Miszkowski'], ['Stanislaus', 'Stanislaus Czikowski']],
        [["Nägeli", 'Näegelin'], ["Schultheiss"]],
        [['Nägeli', 'Näegelin'], ['Christian']],
        [["Naillosius"], ["J.P."]],
        [
            ['Naogeorgus', 'Naogeorg', 'Kirchmeyer', 'Kirchmaier', 'Kirchmeier', 'Kirchmair', 'Neubauer'],
            ['Thomas'],
            "https://de.wikipedia.org/wiki/Thomas_Naogeorg",
            "",
            [[21, 12, 1508], ["Straubing", "Bayern", "Deutschland", SL]],
            [[29, 12, 1563], ["Wiesloch", "Baden-Württemberg", "Deutschland", SL]],
            ["Evangelikaner", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Neythart"], ["Carolus"]],
        [['Niger', 'Negri'], ['Franciscus']],
        [["Nötzli"], ["Markus", "Marcus"]],
        [["Nüscheler"], ["Johann Jakob", "Johann", "Jakob"]],
        [['Öchsli', 'Bovillus'], ['Blasius']],
        [['Obrecht', 'Obprecht', 'Olprech'], ['Georg', 'Jerg', "Jörg"]],
        [['Olevianus'], ['Kaspar', 'Caspar']],
        [['Olisleger', 'von Baars', 'Baars', 'a Baars', 'Bars', 'von Baar', 'de Bars'], ['Adolph', 'Adolphus', 'Adolf']],
        [["Oglethorpe"], ["Owen"]],
        [["Oporin"], [SN]],
        [
            ['Oporin', 'Oporinus', 'Herbster', "Herbst  "],
            ['Johannes', "Johann", "Hans"],
            "https://de.wikipedia.org/wiki/Johannes_Oporinus",
            "/static/images/Portraits_Corr/Oporinus_Johannes.jpg",
            [[25, 1, 1507], ["Basel", "Basel", "Schweiz", SL]],
            [[6, 7, 1568], ["Basel", "Basel", "Schweiz", SL]],
            ["Lehrer", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Orth', 'Orthius'], ['Wigand']],
        [["Ostrorog"], ["Johannes", "Johann", "Hans"]],
        [["Ostrorog"], ["Stanislaus"]],
        [["Ostrorog"], ["Wenzeslaus"]],
        [['Ott', 'Ottheinrich'], ['Heinrich']],
        [['Paceus'], ['Valentin', 'Valentinus']],
        [['Paclesius', 'Paklepka'], ['Stanislaus']],
        [["Pantaleon"], ["Heinrich"]],
        [["Pappus"], ["Hieronymus"]],
        [["Paravicini"], ["Bartholomäus"]],
        [['Parisotus', 'Parisotti', 'Bergomas'], ['Petrus', 'Pietro']],
        [
            ["Parkhurst"],
            ["John"],
            'https://de.wikipedia.org/wiki/John_Parkhurst',
            '/static/images/Portraits_Corr/Parkhurst_John.jpg',
            [[SD, SD, 1512], ['Guildford','Surrey', "England", SL]],
            [[SD, SD, 1575], [SL, SL, SL, SL]],
            ["Bischof", [SD, SD, 1560], [SD, SD, 1675], ["Norwich", "Norfolk", "England", SL]],
        ],
        [["Parkhurst"], ["Margret"]],
        [['Paulus', 'Paul', 'Pawel', 'Pauli', 'Paweł'], ['Gregor', 'Gregorz', 'Gregorius']],
        [['Payan', 'Payanus'], ['Jean', 'Johannes', "Johann", "Hans"]],
        [["Pechius"], ["Sebastian"]],
        [['Pellikan', 'Pellican'], ['Konrad', 'Conrad']],
        [['Perrucel', 'sr. de Beauvoir-La Nocle'], ['Jean de la Fin', 'François, dit de la Rivière']],
        [['Perusinus', 'Bizzarri'], ['Petrus', "Peter"]],
        [["Peyer"], ["Alexander"]],
        [["Peyer"], ["Martin"]],
        [["Pfalzgraf bei Rhein"], ["Christoph"]],
        [["Pfalzgraf von Hessen"], ["Wilhelm"]],
        [["Pfalzgraf von Neuburg"], ["Ottheinrich"]],
        [["Pfalzgraf"], ["Christoph"]],
        [["Pfalzgraf"], ["Ottheinrich"]],
        [["Pfauser"], ["Johannes Sebastian", "Johannes", "Sebastian", "Johann", "Hans"]],
        [["Pfeiffer"], ["Jakob"]],
        [['Pfister', 'Artopoeus'], ['Nikolaus', 'Nicolaus', 'Baling']],
        [["Pfister"], ["Vincenz"]],
        [["Pflüger"], ["Alexander"]],
        [['Philippin', 'Philippinus'], ['Elias', 'Elie']],
        [["Pilkington"], ["James"]],
        [["Pincier"], ["Hermann"]],
        [['Pincier'], ['Johannes', 'Johann', 'Hans']],
        [["Pistorius"], ["Thomas Ulrich", "Thomas", "Ulrich"]],
        [["Platter"], ["Felix"]],
        [['Plançon', 'Plancon', 'Plancius'], ['Guillaume', 'Guilelmus']],
        [['Pluna'], ['Jakob Martin', 'Jacob Martin']],
        [["Ponet"], ["John"]],
        [["Pontisella"], ["Johannes d.J.", "Johannes der Jüngere"]],
        [["Pontisella"], ["Johannes", "Johann", "Hans"]],
        [["Poppius"], ["Menso"]],
        [['Portus', 'Porto'], ['Franciscus', 'Francesco']],
        [["Postellus"], ["Wilhelm"]],
        [['Poullain', 'Polanus'], ['Valérand', 'Valerandus']],
        [['Pournas', 'Pornaxius'], ['Leonhard', 'Leonhart', 'Léonard', 'Leonhardus', 'Leonarthus', "Leonard", "Leonardus"]],
        [['Prazmowski'], ['Andreas', 'Andrzej']],
        [["Quadrio"], ["Ludwig"]],
        [['Radziwill', 'Radziwil', 'Radziwiłł', 'Czarny', 'Graf von Wilna'], ['Nikolaus', 'Mikołaj', 'Olika']],
        [["Ragor"], ["Heinrich"]],
        [["Ramp"], ["Ezechiel"]],
        [['Ramus', 'de la Ramée'], ['Petrus', 'Pierre', 'Peter']],
        [['Rappoltstein', 'von Rappoltstein', 'von Rappoltsweiler'], ['Anna Alexandria', 'Anna', 'Alexandria']],
        [["Rasdorfer"], ["Paul", "Paulus"]],
        [["Ratgeb"], ["Hans", "Johannes", "Johann"]],
        [["Renatus"], ["Camillus"]],
        [["Reniger"], ["Michael"]],
        [["Renty"], ["Anne"]],
        [["Richer"], ["Christophe"]],
        [['Rietmüller', 'Myliagrius'], ['Jakob', 'Jacobus']],
        [["Rietmüller"], ["Johannes", "Johann", "Hans"]],
        [['Rivarius', "Riverius"], ['François', 'Franciscus', 'Francois', 'Franz']],
        [['Röichli', 'Röusch'], ['Jesaias', 'Jesajas', 'Isaia']],
        [["Roding"], ["Nikolaus", "Nicolaus"]],
        [["Roist"], ["Anna"]],
        [['Roll', 'Rollius'], ['Nikolaus', 'Nicolaus']],
        [["Rosenstock"], ["Hans", "Johannes", "Johann"]],
        [['Roset'], ['Michael', 'Michel']],
        [
            ['Rüeger'],
            ["Johannes Jakob", "Johann Jakob", "Hans Jakob", "Johannes Jacob", "Johann Jacob", "Hans Jacob", "Johannes Jacobus", "Johann Jacobus", "Hans Jacobus", "Johannes Jakobus", "Johann Jakobus", "Hans Jakobus", "Johannes", "Johann", "Hans", 'Jakob', 'Jacob', "Jacobus", "Jakobus"],
            "https://de.wikipedia.org/wiki/Johann_Jakob_R%C3%BCeger",
            "",
            [[15, 7, 1548], ["Schaffhausen", "Schaffhausen", "Schweiz", SL]],
            [[19, 8, 1606], ["Schaffhausen", "Schaffhausen", "Schweiz", SL]],
            ['Pfarrer', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
    ],
        [["Rudolfi"], ["Kaspar", "Caspar"]],
        [['Ruffus', 'Ruffy'], ['Jacobus', "Jacob", "Jakob", "Jakobus"]],
        [["Ruinella"], ["Jakob", "Jacob", 'Jacobus', 'Jakobus']],
        [['Rupe', 'de la Roche Chandieu', 'Chandeus'], ['Antoine', 'A.']],
        [['Russel', 'Bedford'], ['Francis', 'Franciscus', 'Earl of', 'François', 'Francois', 'Franz']],
        [['Rust', 'Rust Bernas'], ['Thüring', 'Turingius']],
        [["Ryhiner"], ["Heinrich"]],
        [['Sägisser', 'Segesser'], ['Albrecht']],
        [
            ['Sailer', 'Sayler', 'Seiler', 'Seyler'],
            ['Gereon'],
            'https://www.deutsche-biographie.de/sfz77834.html',
            '/static/images/Portraits_Corr/Sailer_Gereon.jpg',
            [[SD, SD, SD], ['Blumenthal', 'Aichach', 'Deutschland', SL]],
            [[SD, SD, 1563], [SL, SL, SL, SL]],
            ['Doktor', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Arzt', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]]
        ],
        [['Sailer', 'Sayler', 'Seiler', 'Seyler'], ["Raphael"]],
        [["Salet"], ["Wolfgang"]],
        [["Salis"], ["Herkules", "Hercules"]],
        [["Salkyns"], ["William"]],
        [["Sampson"], ["Thomas"]],
        [["Sandys"], ["Edwin"]],
        [['Sarnicki', 'Sarnicius', 'Stadnicki', 'Stadnicius'], ['Stanislaus', 'Stanilaus', 'Stanislaw', 'Stanislaus M']],
        [["Schädler"], ["Isaak"]],
        [["Schädler"], ["Mathias", "Matthias"]],
        [["Schankwitz"], ["Marcel Dietrich", "Marcel", "Dietrich"]],
        [["Schatter"], ["Rando"]],
        [['Schenck', 'Schenk', 'Schenckius', 'Schenkius'], ['Mathias', 'Matthias']],
        [["Scher"], ["Peter d.J.", "Peter der Jüngere"]],
        [["Schertlin"], ["Sebastian"]],
        [["Schlatter"], ["Michael"]],
        [["Schlegel"], ["Johannes", "Johann", "Hans"]],
        [["Schlüsselberger"], ["Gabriel"]],
        [["Schmid"], ["Jost"]],
        [["Schmid"], ["Sebastian"]],
        [["Schmutz"], ["Alexander d.J.", "Alexander der Jüngere"]],
        [['Schneeberger'], ['Anton', 'Antonius']],
        [["Schneewolf"], ["Moritz"]],
        [["Schneider"], ["Peter", "Petrus"]],
        [['Schnyder', 'Sartorius'], ['Abraham']],
        [['Schöpf', 'Schöpfius'], ['Thomas']],
        [["Schöw"], [SN]],
        [["Schürmeister"], ["Benedikt"]],
        [['Schuler', 'Hauptmann Schuler'], ['Fridolin', 'Fridli']],
        [["Schuler"], ["Gervasius"]],
        [["Schuler"], ["Johannes", "Johann", "Hans"]],
        [['Schuler'], ['Paul', 'Paulus']],
        [["Schulherr (Scholarch)"], [SN]],
        [["Schwager"], [SN]],
        [["Seebach"], ["Gregor"]],
        [["Seebach"], ["Margaretha"]],
        [["Seemann"], ["Georg"]],
        [["Seemann"], ["Maximilian"]],
        [["Semly"], ["Konrad", "Conrad"]],
        [['Serin', 'Soerin', 'Soerinus'], ['Leonhard', 'Leonhart', "Leonard", "Leonardus"]],
        [["Sidall"], ["Henry"]],
        [["Sigismund"], ["August", "Augustus"]],
        [['Simburger', 'Süburger'], ['Anton', 'Antonius']],
        [
            ["Simler", "Simmler"],
            ["Josias"],
            'https://de.wikipedia.org/wiki/Josias_Simler',
            '/static/images/Portraits_Corr/Simmler_Josias.jpg',
            [[6, 11, 1530], ["Kappel am Albis", "Zürich", "Schweiz", SL]],
            [[2, 7, 1576], [SL, "Zürich", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Historiker", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Simler"], ["Peter", "Petrus"]],
        [
            ['Skalić', 'Skalich', 'Scalich', 'Scaliger', 'Scalichius', 'Scaligius'],
            ['Pavao', 'Paul', 'Paulus'],
            'https://de.wikipedia.org/wiki/Pavao_Skali%C4%87',
            '/static/images/Portraits_Corr/Scalichius_Paulus.jpg',
            [[SD, SD, 1534], ["Zagreb", "Zagreb", "Kroatien", SL]],
            [[SD, SD, 1575], ["Danzig", "Pommern", "Polen", SL]],
            ["Priester", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Gelehrter", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Skaricza"], ["Máte", "Mate"]],
        [["Skinner"], ["Ralph"]],
        [['Socin', 'Sozin', 'Sozzini'], ['Laelius', 'Lelio']],
        [["Sorsen"], ["Andreas"]],
        [["Sprüngli"], ["Bernhard", "Bernard"]],
        [["Stadler"], ["Jörg"]],
        [["Stancarus"], ["Franciscus", "Franziskus", "Franz"]],
        [['Steiger'], ['Johannes', 'Johann', 'Hans']],
        [['Stephan', 'Štefan'], ['Andreas', 'Ondřej']],
        [['Stephanus', 'Estienne'], ['Robert']],
        [["Stiller"], ["Sebastian"]],
        [["Stipitius"], ["Christoph", "Christopherus", "Christophorus"]],
        [['Stokar', 'Stockar', 'Stockarum'], ['Benedikt']],
        [["Strigel"], ["Viktorin"]],
        [['Stuart', 'Sieur de Vézines'], ['Guillaume']],
        [["Stucki"], ["Johann Wilhelm", "Johann", "Wilhelm", "Johannes", "Hans"]],
        [['Stumpf'], ['Johannes Rudolf', 'Johannes', 'Johann', 'Hans', 'Rudolf', 'Johann Rudolf', 'Hans Rudolf']],
        [["Stupanus"], ["Johann Nikolaus", "Johann", "Nikolaus", "Nicolaus", "Johannes", "Hans"]],
        [["Sturm"], ["Johannes", "Johann", "Hans"]],
        [['Strigelius'], ['Victor', 'Victorinus']],
        [
            ["Sulzer"],
            ["Simon"],
            "https://de.wikipedia.org/wiki/Simon_Sulzer",
            "/static/images/Portraits_Corr/Sulzer_Simon.jpg",
            [[23, 9, 1508], ["Schattenhalb", "Basel", "Schweiz", SL]],
            [[22, 6, 1585], [SL, "Basel", "Schweiz", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], ["Basel", "Basel", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Susliga"], ["Florian"]],
        [["Sylvanus"], ["Johannes", "Johann", "Hans"]],
        [["Sylvio"], ["Bartolomeo"]],
        [["Szadkowski"], ["Andreas"]],
        [['Szichzovinus', 'Szikszoi'], ['Lukas', 'Lukács', "Lucas"]],
        [['Taffin', 'Tafimus'], ['Jean', 'Johannes', "Johann", "Hans"]],
        [["Talmann"], ["Achilles"]],
        [['Tarnowicz', 'Tarnowski'], ['Johannes', "Johann", "Hans"]],
        [['Taurus', 'Stier'], ['Sigismund']],
        [['Terentianus', 'Santerentianus', 'Santerrentianus'], ['Julius', 'Iulius']],
        [["Thamer"], ["Theobald"]],
        [['Theodor', 'Dietrich'], ['Philipp', "Philip"]],
        [['Thoman', 'Thomann'], ['Gregor', 'Gregorius']],
        [['Thomann', 'Thoman'], ['Heinrich']],
        [["Thretius"], ["Christian"]],
        [["Thretius"], ["Christoph", "Christopherus", "Christophorus"]],
        [["Thurius"], ["Mathias", "Matthias"]],
        [['Thyenaeus', 'de Thienes', 'Thienes'], ['Odeardus', 'Odoardus', 'Edouard', 'Eduard']],
        [["Tillmann"], ["Samuel"]],
        [["Tobler"], ["Felix"]],
        [["Tomann"], ["Gregor"]],
        [["Torda"], ["Zsigmond"]],
        [['Tossanus', 'Toussain'], ['Daniel']],
        [['Toxites', 'Schütz'], ['Michael']],
        [["Traber"], ["Johannes", "Johann", "Hans"]],
        [['Traheron'], ['Bartholomäus', 'Bartholomew', 'Bartholomaeus']],
        [["Travers"], ["Johannes"]],
        [["Truber"], ["Primus"]],
        [["Trüb"], ["Heinrich"]],
        [["Tscharner"], ["Hans", "Johannes", "Johann", "Hans"]],
        [['Tschudi'], ['Ägidius', 'Aegidius', 'ägidius', 'Gilg']],
        [["Tschudi"], ["Casper", "Kaspar"]],
        [["Tschudi"], ["Valentin"]],
        [["Tudor", "König"], ["Eduard VI.", "Eduard VI", "Eduard", "Edward VI.", "Edward VI", "Edward"]],
        [['Tuffan', 'Tufanus'], ['Guillaume']],
        [["Turner"], ["Wilhelm"]],
        [["Turner"], ["William"]],
        [["Turrianus"], ["Hieronymus"]],
        [['Uchanski', 'Uchanius'], ['Jakub', "Jakob", "Jacob"]],
        [
            ['Ulmer', 'von Ulm', "Ulmis"],
            ['Johann Konrad', 'Johann Conrad', 'Johannes Konrad', 'Johannes', 'Johann', 'Konrad', 'Conrad'],
            'https://de.wikipedia.org/wiki/Johann_Konrad_Ulmer',
            '/static/images/Portraits_Corr/Johann_Conrad_Ulmer.jpg',
            [[31, 3, 1519], ['Schaffhausen', 'Schaffhausen', 'Schweiz', SL]],
            [[7, 8, 1600], ['Schaffhausen', 'Schaffhausen', 'Schweiz', SL]],
            ['Theologe', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Evangelikaner', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Gelehrter', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ['Reformator', [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]]
        ],
        [["Ulstetter"], ["Johannes", "Johann", "Hans"]],
        [["Ungnad"], ["Johann", "Johannes", "Hans"]],
        [["Ursinus"], ["Zacharias"]],
        [["Usteri"], ["Heinrich"]],
        [
            ['Utenhove', 'van Utenhove van der Gracht', 'van Utenhove'],
            ['Johannes', 'Jan', 'John', 'Johann', "Hans"],
            'https://de.wikipedia.org/wiki/Jan_van_Utenhove',
            '',
            [[SD, SD, 1516], ["Roborst", SL, SL, SL]],
            [[6, 1, 1566], ["London", SL, "England", SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Humanist", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Utenhove'], ['Johannes d.J.', 'Jan d.J.', 'Johannes der Jüngere', 'Jan der Jüngere']],
        [
            ["Vadian", "Vadianus"],
            ["Joachim", "Joachim vom Watt"],
            "https://de.wikipedia.org/wiki/Joachim_Vadian",
            "/static/images/Portraits_Corr/Vadian_Joachim.jpg",
            [[29, 11, 1484], ["St. Gallen", "St. Gallen", "Schweiz", SL]],
            [[6, 4, 1551], ["St. Gallen", "St. Gallen", "Schweiz", SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Bürgermeister", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Arzt", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Vadian"], [SN]],
        [["Valerius"], ["Jacobus"]],
        [["Valois-Angoulême", "König", "Valois", "Angoulême"], ["Franz II.", "Franz II", "Franz"]],
        [['Venetscher'], ['Peter', 'Petrus']],
        [["Venetz"], ["Hans"]],
        [["Venetz"], ["Johannes"]],
        [['Velsius'], ['Justus', 'Just.']],
        [["Vergeri"], ["Aurelio"]],
        [
            ['Vergerius', 'Vergerio', 'Vergerij'],
            ['Petrus Paulus', 'Petrus Paolo', 'Petrus Paollo', 'Petrus Pavel',
             'Petro Paulus', 'Petro Paolo', 'Petro Paollo', 'Petro Pavel',
             'Pietro Paulus', 'Pietro Paolo', 'Pietro Paollo', 'Pietro Pavel', 'Pier Paulus', 'Pier Paolo', 'Pier Paollo', 'Pier Pavel', 'Petrus', 'Pietro', 'Petro', 'Pier', 'Paolo', 'Paullo', 'Paulus', 'Pavel'],
            "https://de.wikipedia.org/wiki/Pietro_Paolo_Vergerio",
            "/static/images/Portraits_Corr/Vergerio_Petro.jpg",
            [[SD, SD, 1498], [SL, SL, "Italien", SL]],
            [[4, 10, 1565], ["Tübingen", "Baden-Württemberg", "Deutschland", SL]],
            ["Geistlicher", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Pfarrer", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Priester", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Theologe", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Bischof", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [['Vermigli'], ['Peter Martyr', 'Pietro Martyr', 'Petrus Martyr', 'Peter Martire', 'Petrus Martire', "Pietro Martire", "Pietro", 'Peter', 'Petrus', 'Martyr', 'Martire']],
        [["Vietor"], ["Heinrich"]],
        [["Vigierius"], ["J."]],
        [["Vincent"], ["Antoine"]],
        [['Viret'], ['Pierre', 'Peter']],
        [['Vitrelin', 'Vitrelinus', 'Witrelin'], ['Alexander']],
        [['Vogel', 'Avienus'], ['Jakob']],
        [['Vogler'], ['Hans', 'Johann', 'Johannes']],
        [["Vogler"], ["Johannes d.Ä.", "Johannes der Ältere", "Johann d.Ä.", "Johann der Ältere", "Hans der Ältere", "Hans d.Ä."]],
        [["Vogler"], ["Johannes d.J.", "Johannes der Jüngere", "Johann d.J.", "Johann der Jüngere", "Hans der Jüngere", "Hans d.J."]],
        [["Volmar"], ["Melchior"]],
        [['Vogt'], ['Simprecht', 'Simpert']],
        [["von Baden-Hochberg"], ["Anna"]],
        [["von Below", "Below"], ["Georg"]],
        [["von Berckheim", "Berckheim"], ["Balthasar"]],
        [["von Bernhausen", "Bernhausen"], ["Wilhelm"]],
        [["von Brunn"], ["Bonaventura"]],
        [["von Cham"], ["Bernhard"]],
        [['von Diesbach', "Diesbach"], ['Nikolaus', 'Niklaus']],
        [['von Dörnberg', 'von Dürnberg', 'Dürnberg', 'Dörnberg'], ['Adolf Wilhelm', 'Adolf', 'Wilhelm']],
        [['von der Pfalz', 'Pfalzgraf am Rhein', 'Pfalzgraf', 'Pfalzgraf bei Rhein', 'Pfalzgraf bei Rhein'], ['Friedrich', 'Friedrich III.', 'der Fromme']],
        [["von Ellerbach", "Ellerbach"], ["Madlena"]],
        [["von Erbach", "Erbach"], ["Eberhard"]],
        [["von Erlach", "Erlach"], ["Hans Rudolf", "Johannes Rudolf", "Johann Rudolf", "Johannes", "Johann", "Hans", "Rudolf"]],
        [["von Erlach", "Erlach"], ["Wolfgang"]],
        [["von Fleckenstein", "Fleckenstein"], ["Heinrich"]],
        [["von Freiberg", "Freiberg"], ["Wilhelm"]],
        [["von Freyberg", "Freyberg"], ["Pankraz"]],
        [["von Friesland"], ["Anna"]],
        [["von Fölkersam", "Fölkersam"], ["Friedrich"]],
        [["von Grafeneck"], ["Klaus"]],
        [["von Hallwyl"], ["Hartmann"]],
        [["von Heideck", "Heideck", "von Heidegg", "Heidegg"], ["Johann Christoph", "Johann", "Christoph", "Johannes", "Hans"]],
        [["von Heidegg", "von Heideck", "Heidegg", "Heideck"], ["Hans-Christoph", "Hans Christoph"]],
        [["von Hessen"], ["Philipp d.J.", "Philipp der Jüngere"]],
        [["von Hessen"], ["Philipp d.Ä.", "Philipp der Ältere"]],
        [["von Hohensax", "Hohensax"], ["Johann Philipp", "Johann", "Philipp", "Ulrich Philip", "Philip"]],
        [['von Hohensax', 'Hohensax', 'Sax'], ['Ulrich', 'Ulrich Philipp', 'Philipp', "Ulrich Philip", "Philip"]],
        [["von Hövel", "von Hoevel", "Hövel", "Hoevel"], ["Otto"]],
        [["von Karpfen", "Karpfen"], ["Balthasar"]],
        [["von Landenberg", "Landenberg"], ["Ulrich"]],
        [['von Laubenberg', 'Laubenberg'], ['Johannes Wilhelm', 'Johann Wilhelm', 'Hans Wilhelm', 'Johannes', 'Wilhelm', 'Johann', 'Hans']],
        [["von Lehwald"], ["Balthasar"]],
        [["von Lupfen", "zu Lupfen", "Lupfen"], ["Justina"]],
        [['von Mülinen', 'von Mülynen', 'Mülinen', 'Mülynen'], ['Beat Ludwig', 'Beat', 'Ludwig']],
        [["von Oldenburg", "König"], ["Christian III.", "Christian III", "Christian", "Christian III.", "Christian III", "Christian"]],
        [["von Pappenheim", "zu Pappenheim", "Pappenheim"], ["Christoph"]],
        [["von Pappenheim", "zu Pappenheim", "Pappenheim"], ["Philipp"]],
        [["von Preussen"], ["Albrecht"]],
        [["von Radelo", "Radelo"], ["Reinhardt"]],
        [["von Rappoltstein", "Rappoltstein"], ["Egenolf"]],
        [['von Rappoltstein', 'von Heideck', 'Rappoltstein', 'Heideck'], ['Elisabeth', 'Else']],
        [["von Rappoltstein", "Rappoltstein"], ["Maria"]],
        [["von Rümlang", "Rümlang"], ["Eberhard"]],
        [["von Sachsen", "Sachsen"], ["Friedrich"]],
        [
            ["von Salis", "Salis"],
            ["Friedrich"],
            'https://de.wikipedia.org/wiki/Salis_%28Adelsgeschlecht%29',
            '/static/images/Portraits_Corr/Salis-Wappen.png',
            [[SD, SD, 1512], [SL, SL, SL, SL]],
            [[14, 6, 1570], [SL, SL, SL, SL]],
            ["Botschafter", [SD, SD, SD], [SD, SD, SD], ["Venedig", "Venetien", "Italien", SL]]
        ],
        [["von Salis", "Salis"], ["Herkules", "Hercules"]],
        [["von Salis", "Salis"], ["Johann", "Johannes", "Hans"]],
        [["von Salis", "Salis"], ["Rudolf"]],
        [["von Salis", "Salis"], [SN]],
        [["von Savoyen", "Savoyen"], ["Margareta"]],
        [["von Sayn zu Wittgenstein", "von Sayn zu Wittgenstein", "von Sayn", "Sayn"], ["Ludwig der Ältere", "Ludwig d.Ä."]],
        [["von Schauenstein", "Schauenstein"], ["Remigius"]],
        [["von Schwendi", "Schwendi"], ["Lazarus"]],
        [["von Starkenburg", "Starkenburg"], ["Nikolaus", "Nicolaus"]],
        [["von Stetten"], ["Albert"]],
        [['von Stetten', 'Stetten'], ['Georg']],
        [['von Stetten', 'Stetten'], ['Georg d.J.', 'Georg der Jüngere']],
        [["von Stetten"], ["Regina Georgiu", "Regina", "Georgiu"]],
        [["von Strünckter", "Strünckter"], ["Georg"]],
        [["von Thessalonich", "Thessalonich"], ["Demetrius"]],
        [["von Ulm"], ["Heinrich II."]],
        [
            ["Valois-Angoulême", "von Valois", 'Valois', "Herzog von Anjou", "Henri von Valois", "Walezy"],
            ["Heinrich III.", "Heinrich III", "Alexandre-Édouard", "Henri III.", "Henri III", "Henri", "Henryk"],
            "https://de.wikipedia.org/wiki/Heinrich_III._(Frankreich)",
            "/static/images/Portraits_Corr/Henri_III_roi_de_france.jpg",
            [[19, 9, 1551], [SL, SL, SL, SL]],
            [[2, 8, 1589], [SL, SL, SL, SL]],
            ["König", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Frankreich", SL]],
        ],
        [
            ["Valois-Angoulême", "von Valois", "König von Frankreich", "König"],
            ["Heinrich II.", "Heinrich II", "Henri II.", "Henri II"],
            'https://de.wikipedia.org/wiki/Heinrich_II._(Frankreich)',
            '/static/images/Portraits_Corr/Henri_II_roi_de_France.jpg',
            [[31, 3, 1519], [SL, SL, SL, SL]],
            [[10, 7, 1559], [SL, SL, SL, SL]],
            ["König", [SD, SD, SD], [SD, SD, SD], [SL, SL, "Frankreich", SL]],
        ],
        [["von Wied", "Wied"], ["Hermann"]],
        [["von Wittgenstein", "Wittgenstein"], ["Ludwig"]],
        [
            ['von Württemberg', 'Württemberg', 'von Württemberg-Mömpelgard', 'von Württemberg-Mömpelgart', 'Württemberg', 'Württemberg-Mömpelgart', 'Graf von Württemberg', 'Graf von Württemberg-Mömpelgard', 'Graf von Württemberg-Mömpelgart', 'Graf Württemberg', 'Graf Württemberg-Mömpelgart'],
            ['Georg', "Georg I.", "Georg I", "der Vorsichtige"],
            "https://de.wikipedia.org/wiki/Georg_I._(W%C3%BCrttemberg-M%C3%B6mpelgard)",
            "/static/images/Portraits_Corr/von_Württemberg_Georg.jpg",
            [[4, 2, 1498], [SL, SL, SL, SL]],
            [[17, 7, 1558], [SL, SL, SL, SL]],
        ],
        [['Waidner', 'Hertin', 'Waydner', 'Weidner'], ['Katharina', 'Catharina']],
        [['Waidner', 'Waydner', 'Weidner', 'Waidnerus'], ['Wolfgang']],
        [["Walder"], ["Johannes Konrad", "Johann Konrad", "Hans Konrad", "Johannes Conrad", "Johann Conrad", "Hans Conrad", "Johannes", "Johann", "Hans", "Konrad", "Conrad"]],
        [["Wardesius"], ["Stanislaus"]],
        [['Weidner', 'Vueydnerus'], ['Johannes', "Johann", "Hans"]],
        [["Wellenberg"], ["Hans", "Johannes", "Johann"]],
        [["Welser"], ["Hans", "Johannes", "Johann"]],
        [["Welser"], ["Philipp", "Philip"]],
        [["Westheimer"], ["Bartholomäus"]],
        [["Wetter"], ["David"]],
        [["Wetzler"], ["Martin", "Martinus"]],
        [["Wiburne"], ["Percival"]],
        [["Wichser"], ["Ludwig"]],
        [["Wick"], ["Johann Jakob"]],
        [["Wilhelmi"], ["Valentin"]],
        [['Willer', 'Wüller'], ['Georg', 'Jörg']],
        [["Willi"], ["Stephan"]],
        [["Willing"], ["Johannes", "Johann", "Hans"]],
        [["Willock"], ["John"]],
        [["Wimpfer"], ["Georg"]],
        [["Winzürn"], ["Johannes", "Johann", "Hans"]],
        [['Wirth', "Wirt", 'Hospinian', 'Hospinianus', 'Hospinianus'], ['Adrian']],
        [['Wisamer'], ['Baptist Johannes', "Bapt. Johannes", 'Babt. Johannes', 'Baptist', 'Johannes']],
        [['Wissenburg', 'Wißenburg'], ['Wolfgang']],
        [['Withers', 'Witherus'], ['George', 'Georges', 'Georg']],
        [["Wolf"], ["Abraham"]],
        [["Wolf"], ["Heinrich"]],
        [["Wolf"], ["Johannes", "Johann", "Hans"]],
        [["Wolf"], ["Kaspar", "Caspar"]],
        [['Wolfhard', 'Wolfhart'], ['Ulrich']],
        [['Wüst', 'Turpilius', 'Zollicovensis'], ['Klaus', 'Nicolaus', 'Nikolaus']],
        [['Wunderlich', 'de Merveilleux'], ['Hans', 'Jean', "Johann", "Johannes"]],
        [['Xylander', 'Holzmann'], ['Wilhelm']],
        [['Zacius', 'Zak'], ['Simon']],
        [
            ['Zanchi', 'Zanchus', 'Zanchius'],
            ['Hieronymus', 'Hieronimo', 'Hieronymo', 'Girolamo', 'Girolami'],
            'https://de.wikipedia.org/wiki/Girolamo_Zanchi',
            '/static/images/Portraits_Corr/Girolami-Zanchi.jpg',
            [[2, 2, 1516], ["Alzano Lombardo", "Lombardei", "Italien", SL]],
            [[19, 11, 1590], ["Heidelberg", SL, SL, SL]],
            ["Prediger", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
            ["Reformator", [SD, SD, SD], [SD, SD, SD], [SL, SL, SL, SL]],
        ],
        [["Zehender"], ["Hans", "Johannes", "Johann"]],
        [['Zehnder', 'Zehender'], ['Samuel']],
        [["Zehender"], ["Ludwig"]],
        [["Zemlinus"], ["Laurentius"]],
        [["Ziegler"], ["Ambrosius"]],
        [["Ziegler"], ["Hans", "Johannes", "Johann"]],
        [["Zoller"], ["Agatha"]],
        [["Zürcher"], [SN]],
        [["Züst"], ["Heini"]],
        [["Zuleger"], ["Wenzeslav"]],
        [['Zurkinden', 'Zerchintes', 'Zitinius'], ['Nikolaus', 'Nicolaus']],
        [["Zwick"], ["Johannes", "Johann", "Hans"]],
        [["Zwick"], ["Konrad", "Conard"]],
        [["Zwinger"], ["Theodor"]],
        [["Zwingli"], ["Ulrich Huldrych III.", "Ulrich III.", "Huldrych III.", "Huldrych", "Ulrich"]],
        [["zu Tübingen", "Gräfin zu Tübingen", "von Tübingen", "Gräfin von Tübingen"], ["Katharina"]],
        [['zum Camph', 'thom Camph', 'Camph', 'Camp', 'zum Camp', 'tom Camp'], ['Gerhard']],
        [['zum Lamb', 'zum Lamm', 'Lamb', 'Lamm', 'Agninus'], ['Hieronimus', 'Hieronymus']],
        [[SN], ["Eduard VI."]],
        [[SN], ["Gabriel"]],
        [[SN], ["Heinrich II."]],
        [[SN], ["Junker"]],
        [[SN], ["Michel"]],
        [[SN], ["Paul"]],
    ]

    """
    ARCHIVES = [
        ["Zürich StA"],
        ["Zürich ZB"],
        ["Genf BPU"],
        ["Strassburg BNU"],
        ["Basel UB"],
        ["St. Gallen KB"],
        ["München BStB"],
        ["Bern StA"],
        ["Bern BB"],
        ["Genf MHR"],
        ["Schaffhausen StB"],
        ["Paris BSG"],
        ["Paris BN"],
        ["Marburg HStA"],
        ["Dublin TC"],
        ["Schaffhausen StA"],
        ["London BM"],
        ["Chur StA"],
        ["Strassburg AST"],
        ["Winterthur StB"],
        ["London Lambeth Palace"],
        ["Emden BGK"],
        ["Zofingen StB"],
        ["Cambridge UL"],
        ["Gotha FB"],
        ["Hamburg StUB"],
        ["Berleburg FA"],
        ["Colmar, Archives départ."],
        ["Genf"],
        ["Krakau BJ"],
        ["Leiden UB"],
        ["Oxford BL"],
        ["Cambridge CCC"],
        ["Utrecht BRU"],
        ["Den Haag Koninklijk Huisarchief"],
        ["Dresden StA"],
        ["Kilchberg, Gemeindearchiv"],
        ["Prag StUA"],
        ["Bern BurgerB"],
        ["Chur, Synodal- und Kirchenratsarchiv"],
        ["Detmold, Lippische Landesbibliothek"],
        ["Genf, Archives d\'Etat"],
        ["Strassburg"],
        ["Stuttgart Hauptstaatsarchiv"],
        ["Edinburgh Univ. Library"],
        ["London, Archiv der Belg. Kirche, Austin Friars"],
        ["Zürich, Orelli-Archiv"],
        ["\"apud Cl. decanum Usteri\""],
        ["\"in Bibl. Huldericiana\""],
        ["(Berlin, Slg. B. Friedlaender)"],
        ["(West-)Berlin, Staats B, Pr. Kulturbesitz (früher Pr StB)"],
        ["A. Porta"],
        ["Amsterdam BVU = Bibliotheek der Vrijen Universiteit, Mr. H. Bos-Bibliothek"],
        ["Archives of the Belgic Church, Austin Friars, London"],
        ["BGE (Genf)"],
        ["Basel StA"],
        ["Berlin, DSB"],
        ["Berlin, Staatsbibl. Preuß. Kulturbesitz,"],
        ["Bern"],
        ["Bern StB"],
        ["Bern Stadtbibl."],
        ["Breitingers Bibliothek"],
        ["Cambridge, Emmanuel College,"],
        ["Collection Sarrau"],
        ["Genf Archives d\'Etat"],
        ["Genf, Archives d\'Etat [=AEG]"],
        ["Glarus, Landesarchiv"],
        ["Göttigen, Staatliches Archivlager"],
        ["Hannover Stadtarchiv (ehemals Kestner Museum)"],
        ["IRG"],
        ["Kassel, Murhardsche + Landes B"],
        ["Kassel, Murhardsche B der Stadt Kassel und Landesbibliothek"],
        ["Kopenhagen KB"],
        ["Kopenhagen, Reichsarchiv"],
        ["Leyden"],
        ["Leyden, Cod. Perigon."],
        ["London BL"],
        ["London Dr. Williams Library"],
        ["London Dutch Reformed Church"],
        ["London Public Record Office"],
        ["London, Public Recort Office"],
        ["Neuenburg, BPast"],
        ["New York The Pierpont Morgan Library"],
        ["Paris BFP (= Bibl. de la SHPF)"],
        ["Paris SHPF"],
        ["Philadelphia, The Hist. Society of Pennsylvania"],
        ["Pozen/Poznan Archiwum Panstwowe"],
        ["Simler 78"],
        ["St. Gallen, Stadtarchiv"],
        ["Stadtbibliothek Breslau"],
        ["Stuttgart HStA"],
        ["Weimar StA"],
        ["Winterthur StA"],
        ["Wittenberg Lutherhalle"],
        ["Wolfenbüttel HAB"],
        ["Zizers Archiv v. Salis"],
        ["Zürich Stadtarchiv"]
    ]
    """
