#!/anaconda3/bin/python3.7
# -*- coding: utf-8 -*-
# config.py
# Bernard Schroffenegge20th of October, 2019

import os
basedir = os.path.abspath(os.path.dirname(__file__))


class Config(object):

    APP_NAME = "KoKoS-Bullinger"
    ADMIN = 'Admin'
    ADMINS = [ADMIN, 'mvolk', 'Patricia']
    VIP = [ADMIN, 'mvolk', 'Patricia', 'Judith Steiniger', 'Peter Rechsteiner', 'PeterOpitz']

    SECRET_KEY = os.environ.get('SECRET_KEY') or 'the010gy_sucks:P'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    BULLINGER_UI_PATH = os.environ.get('BULLINGER_UI_PATH') or 'http://bullinger.raphaelm.ch/'
    BULLINGER_MAP_PATH = os.environ.get('BULLINGER_MAP_PATH') or 'http://bullinger-map.raphaelm.ch/'

    # status cards
    S_OPEN = 'offen'
    S_UNKNOWN = 'unklar'
    S_FINISHED = 'abgeschlossen'
    S_INVALID = 'ungültig'

    # null values
    SD = 's.d.'  # sine die
    SN = 's.n.'  # sine nomine
    SL = 's.l.'  # sine loco
    NONE = '-'  # language stats

    BASIC_AUTH_USERNAME = 'Admin'  # fake
    BASIC_AUTH_PASSWORD = '_whatever0987!'  # leads to nowhere

    # correspondence plot
    BAR_WIDTH = 0.5
    OFFSET = 5

    URL_ESC = "#&&"

    # DB export
    PATH_DB_EXPORT = "Data/DB_export/"

    PATH_DB_ARCHIVE = "doc_archives.txt"
    PATH_DB_DOC_TYPES = "doc_types.txt"
    PATH_DB_DOCUMENT = "documents.txt"

    PATH_DB_PLACES = "places.txt"
    PATH_DB_COUNTRIES = "place_countries.txt"
    PATH_DB_COMPLEX_LOCATIONS = "place_complex.txt"

    PATH_DB_PERSONS = "corr_persons.txt"
    PATH_DB_TITLES = "corr_titles.txt"
    PATH_DB_COLLECTIVE = "corr_institutions.txt"

    PATH_DB_ADD_PERSONS = "add_persons.txt"
    PATH_DB_ADD_TITLES = "add_titles.txt"
    PATH_DB_ADD_INSTITUTIONS = "add_institutions.txt"

    PATH_DB_BIBLIOGRAPHY = "bibliographies.txt"
    PATH_DB_LITERATURE = "literature.txt"
    PATH_DB_PRINT = "prints.txt"

    PATH_DB_LANGUAGE = "countries.txt"
    PATH_DB_LANGUAGE = "languages.txt"
    PATH_DB_DOC_LANG = "doc_language.txt"

    PATH_DB_SENTENCES = "sentences.txt"
    PATH_DB_REMARK_TYPES = "note_types.txt"
    PATH_DB_NOTES = "notes.txt"

    PATH_DB_AUTHORIZATION = "user_group.txt"
    PATH_DB_USER = "user.txt"
    PATH_DB_PAGE_VIEWS = "page_views.txt"
    PATH_DB_PAGE_MODE = "page_mode.txt"

    TITLES = [  # title, group
        ["Abgeordneter", "Abgeordnete"],
        ["Adliger", "Adel"],
        ["Ältester", "Älteste"],
        ["Bischof", "Bischöfe"],
        ["Burger", "Burger"],
        ["Bürgermeister", "Bürgermeister"],
        ["Bruder", "Brüder"],
        ["Christ", "Christen"],
        ["Dekan", "Dekane"],
        ["Evangelikaner", "Evangelikaner"],
        ["Examinator", "Examinatoren"],
        ["Flüchtling", "Flüchtlinge"],
        ["Fürst", "Fürsten"],
        ["Geistlicher", "Geistliche"],
        ["Gelehrter", "Gelehrte"],
        ["Gläubiger", "Gläubige"],
        ["Gnädiger Herr", "Gnädige Herren"],
        # ["Graf", "Grafen"],
        # ["Gräfin", "Gräfinnen"],
        ["Herr", "Herren"],
        # ["Herzog", "Herzoge"],
        # ["Herzog", "Herzöge"],
        ["Kirchendiener", "Kirchendiener"],
        ["Kirchenleiter", "Kirchenleiter"],
        ["Kirchenrat", "Kirchenräte"],
        ["Kolloquent", "Kolloquenten"],
        ["König", "Könige"],
        ["König", "Könige"],
        ["Lehrer", "Lehrer"],
        ["Pastor", "Pastoren"],
        ["Meier", "Meier"],
        ["Pasteur", "Pasteurs"],
        ["Pfarrer", "Pfarrer"],
        ["Prediger", "Prediger"],
        ["Predikant", "Predikanten"],
        ["Prädikant", "Prädikanten"],
        ["Professor", "Professoren"],
        ["Propst", "Pröpste"],
        ["Prädikant", "Prädikanten"],
        ["Päpstlicher Gesandter", "Päpstliche Gesandte"],
        ["Rat", "Räte"],
        ["Ratsherr", "Ratsherren"],
        ["Rechenherr", "Rechenherren"],
        ["Schulherr", "Schulherren"],
        ["Schulmeister", "Schulmeister"],
        ["Schultheiss", "Schultheissen"],
        ["Schulverordneter", "Schulverordnete"],
        ["Senior", "Senioren"],
        ["Syndic", "Syndics"],
        ["Staatsmann", "Staatsmänner"],
        ["Statthalter", "Statthalter"],
        ["Verfolgter Gläubiger", "Verfolgte Gläubige"],
        ["Verordneter Examinator", "Verordnete Examinatoren"],
        ["Verordneter", "Verordnete"],
        ["Vorsteher", "Vorsteher"]
    ]

    INSTITUTIONS = [
            ["das Augsburger Bekenntnis", "die Augsburger Bekenntnisse"],
            ["Belgisch-Deutsche Fremdengemeinde", "Belgisch-Deutsche Fremdengemeinden"],
            ["Evangelische Gemeinde", "Evagelische Gemeinden"],
            ["Flüchtlingsgemeinde", "Flüchtlingsgemeinden"],
            ["Fremdengemeinde", "Fremdengemeinden"],
            ["Freiamt", "Freiämter"],
            ["Fremdkirche", "Fremdkirchen"],
            ["Fremdenkirche", "Fremdenkirchen"],
            ["Gemeinde", "Gemeinden"],
            ["Kapitel", "Kapitel"],
            ["Kapitel des Grossmünsterkapitels", "Kapitel der Grossmünster"],  # sic
            ["Kapitel des Grossmünsterstifts", "Kapitel der Grossmünsterstifte"],
            ["Kirche", "Kirchen"],
            ["La Compagnie des Pasteurs", "Les Compagnies des Pasteures"],
            ["Neue Zeitung", "Neue Zeitungen"],
            ["Polnisch-Litauischer Reichstag (Sejm)", "Polnisch-Litauische Reichstage (Sejm)"],
            ["Synode", "Synoden"],
            ["Ratskomission"],
            ["Reformierte Kirche", "Reformierte Kirchen"],
            ["Volk", "Völker"]
        ]

    COUNTRIES = [
        ["Belgien"],
        ["Deutschland", "Teutschland", "Oberdeutschland"],
        ["Dänemark"],
        ["England"],
        ["Frankreich"],
        ["Friesland", "Ost-Friesland"],
        ["Italien"],
        ["Litauen"],
        ["Polen", "Klein-Polen", "Kleinpolen", "Polen (Klein-Polen)"],
        ["Rumänien"],
        ["Russland"],
        ["Siebenbürgen"],
        ["Ungarn"],
        ["Österreich"],
    ]

    COMPLEX_LOCATIONS = [
        "die Städte der Eidgenossenschaft",
        "Welschland",
        "die drei Bünde",
        "die vier evangelischen Städte",
        "untere kurfürstliche Pfalz"
    ]

    LANGUAGES = [
        ["la", "de", "Latein"],
        ["de", "de", "Deutsch"],
        ["fr", "de", "Französisch"],
        ["en", "de", "Englisch"],
        ["it", "de", "Italienisch"],
        ["el", "de", "Griechisch"],
    ]

    ALIAS = [
        [['Abel'], ['Johannes', 'Johann', 'John', 'Hans']],
        [['Acronius'], ['Phrysius Johannes', 'Frisius Johannes', 'Johannes', 'Frisius Johann', 'Phrysius Johann', 'Johann', 'Frisius John', 'Phrysius John', 'John']],
        [['Adlischwyler', 'Adelschwyler', 'Adlischwiler', 'Adelschwiler'], ['Johannes', 'Johann', 'Johan', 'Hans']],
        [['Adlischwyler', 'Adelschwyler', 'Adlischwiler', 'Adelschwiler'], ['Johannes Jakob', 'Johannnes', 'Hans Jakob', 'Hans', 'Jakob', 'Johannes']],
        [['Meyer', 'Agricola'], ['Lorenz', 'Laurentius', 'Laurenz']],
        [['Aichinger'], ['Christoph', 'Christophorus']],
        [['Altieri'], ['Baldassare', 'Balthasar', 'Baldassar']],
        [['Ampelander', 'Rebmann'], ['Valentin']],
        [['Anastasius', 'Versteghe', 'Veluanus'], ['Johannes', 'Jan Gerritszoon', 'Anastasius Johannes']],
        [['Apriolus', 'Eberli', 'Eberlin'], ['Heinrich']],
        [['Bachofen', 'Backofen'], ['Mathias', 'Matthias']],
        [['Banc', 'Bancus'], ['Arnaud', 'Arnulphus']],
        [['Barthelot', 'Barthelottus'], ['John', 'Johannes']],
        [['Baudouin', 'Bauduin', 'Balduinus'], ['François', 'Francois']],
        [['Beccaria'], ['Johannes', 'Giovanni']],
        [['Bechlin'], ['Johannes', 'Johann']],
        [['Beck', 'Becks', 'Beccius'], ['Dietrich', 'Theod. Laurentius']],
        [['Bersius', 'Bertschi'], ['Marcus']],
        [['Bertlin', 'Berthlinus'], ['Bartholomäus', 'Bartholomaeus']],
        [['Besardus', 'Betschart'], ['Martin', 'Martinus']],
        [['Birckmann', 'Birchmann', 'Birchman'], ['Johannes']],
        [['Blarer', 'Blaurer'], ['Ambrosius']],
        [['Blasius', 'Blaise'], ['Marcuard']],
        [['Blum', 'Florus'], ['Johannes']],
        [['Bochetel', 'Episcopus'], ['Bernardin', 'Rhedonenis']],
        [['Bonett', 'Bellinchetti'], ['Franz']],
        [['Bramburg', 'Bramburgius'], ['Paul', 'Pavel', 'Paulus']],
        [['Brunner', 'Fonteius', 'Fontejus'], ['Fridolin']],
        [['Bullinger', 'Bullinger-Adlischwyler', 'Bullinger-Adlischwiler', 'Bullinger-Adelschwiler', 'Adelschwiler'], ['Anna']],
        [['Budny'], ['Simon', 'Szymon']],
        [['Bullinger'], ['Heinrich d.J.', 'Heinrich der Jüngere']],
        [['Bullinger'], ['Heinrich d.Ä.', 'Heinrich der Ältere']],
        [['Bullinger'], ['Johann', 'Johannes']],
        [['Butler'], ['Heinrich', 'Henry']],
        [['Campell', 'Chiampell'], ['Ulrich', 'Durich', 'Duri', 'Durisch']],
        [['Campensis', 'Camph', 'ten Camph', 'von Kampen'], ['Petrus', 'Petrus Tom']],
        [['thom Camph', 'Camph', 'Camp', 'zum Camph', 'zum Camp', 'tom Camp'], ['Gerhard']],
        [['Caraccioli'], ['Galeazzo', 'Galeatius']],
        [['Chytraeus', 'Chyträus'], ['David']],
        [['Cirlerus', 'Zirler', 'Cirler'], ['Stephan', 'Steffanus']],
        [['Cleber', 'Kleber'], ['Eusebius', 'Euseb']],
        [['Cnipius', 'Knip'], ['Johannes']],
        [['Cousin', 'Cognatus'], ['Gilbert', 'Gilbertus']],
        [['Coignet'], ['Matthieu', 'Matthaeus', 'Laberius']],
        [['Coignet'], ['Matthieu d.J.', 'Matthieu der Jüngere', 'Mattheus d.J.', 'Mattheus der Jüngere']],
        [['Coignet'], ['Matthieu d.Ä.', 'Matthieu der Ältere', 'Mattheus d.Ä.', 'Mattheus der Ältere']],
        [['Collinus', 'Ambiel'], ['Caspar', 'Kaspar']],
        [['Comes', 'Comte'], ['Beatus']],
        [['Cook', 'Cooke'], ['Anthony', 'Anthonius']],
        [['Crato', 'Crato von Krafftheim'], ['Johannes']],
        [['Crespin', 'Crispin', 'Crispinus'], ['Jean']],
        [['Cruciger', 'Cruzinger', 'Krzyzak'], ['Felix']],
        [['Cruxceus', 'Crois', 'de la Croix', 'Cruxaeus'], ['Nicolas']],
        [['Curio', 'Curione'], ['Coelius', 'Coelio', 'Caelio', 'Celio', 'Secundo', 'Secundus', 'Secondo', 'Coelius Secundo', 'Coelio Secundo', 'Caelio Secundo', 'Celio Secundo', 'Coelius Secundus', 'Coelio Secundus', 'Caelio Secundus', 'Celio Secundus', 'Coelius Secondo', 'Coelio Secondo', 'Caelio Secondo', 'Celio Secondo']],
        [['Daius', 'Day'], ['Johannes', 'John']],
        [['Danmatter', 'Dammatter'], ['Christian']],
        [['Dasypodius'], ['Konrad', 'Conrad']],
        [['Dathenus'], ['Petrus', 'Peter']],
        [['De La Borde', 'Bordesius'], ['Jacques', 'Jacobus']],
        [['Del Corro', 'Corranus'], ['Antonio', 'Antonius']],
        [['Delescourre', 'Scorranus'], ['Jean', 'Johannes']],
        [['Della Rovere', 'von Mailand', 'Della Rovere da Milano', 'Milanese'], ['Giulio', 'Julius']],
        [['des Gallars', 'Des Gallars', 'Gallatius', 'Gallars', 'Gallasius'], ['Nikolaus', 'Nicolas']],
        [['Desouches', 'Disonthes'], ['Léodegar', 'Leodigarius']],
        [['Despota', 'Despotul', 'Fürst Moldau und Walachei'], ['Jacoubs Heraclides', 'Jacob Eraclide']],
        [['Dluska', 'Dluska-Kottwitz'], ['Agnes']],
        [['Dluska', 'Dluska-Kottwitz'], ['Nikolaus']],
        [['Du Moulin', 'Molinius'], ['Claude', 'Claudius']],
        [['Dumont', 'Montanus'], ['Luc', 'Lucas']],
        [['Duno', 'Dunus'], ['Taddeo', 'Thaddaeus']],
        [['Dürnhofer'], ['Laurenz', 'Laurentius', 'Laurent']],
        [['Egli', 'Iconius'], ['Tobias']],
        [['Ehem'], ['Christoph', 'Christopherus']],
        [['Erastus', 'Erast'], ['Thomas']],
        [['Erb'], ['Matthias', 'Mathias']],
        [['Ewich'], ['Johannes', 'Johann']],
        [['Fabri', 'Faber', 'Libertet'], ['Christophe', 'Christoph']],
        [['Fabricius', 'Düsseldorpianus', 'Orion', 'Faber'], ['Karl', 'Carolus', 'Janus', 'Engelbert']],
        [['Fehr', 'Fer'], ['Jakob']],
        [['Falais', 'Falesius', 'von Burgund', 'de Bourgogne', 'Burgundia'], ['Jakob', 'Jacques']],
        [['Fejérthóy', 'Feyerthoy', 'Fejérthoy', 'Fejértóy'], ['Johannes', 'János']],
        [['Finck'], ['Konrad', 'Conrad']],
        [['Finsler', 'Vinslerus'], ['Josua', 'Josias']],
        [['Foxe'], ['John', 'Johannes']],
        [['Franciscus', 'Francisco', 'Franz'], ['Dryander', 'Dryander de Enzinas']],
        [['Frei', 'Freigius'], ['Johann Thomas', 'Thomas', 'Johann']],
        [['Frey', 'Frei', 'Liberius', 'Liévin', 'Sr de Beaulieu'], ['Johann Leopold', 'Johann', 'Leopold', 'Johannes', 'Jean']],
        [['Frölich', 'Laetus'], ['Georg']],
        [['Funck', 'Funk', 'Funccius', 'Fedmiger'], ['Johannes', 'Johan', 'Johann']],
        [['Gadius', 'Gaddi'], ['Paulus']],
        [['Garnerius', 'Garnier'], ['Johannes', 'Jean']],
        [['Georg'], ['Mönhart', 'Monnhart']],
        [['Geßner', 'Gessner'], ['Konrad', 'Conrad']],
        [['Gilowski', 'Gilovius'], ['Pawel', 'Paul', 'Paulus']],
        [['Gimper', 'Gymper'], ['Kaspar']],
        [['Grasser', 'Grasserus'], ['Jonas']],
        [['Grataroli', 'Gratarolus'], ['Wilhelm', 'Guglielmo', 'Guilhelmus', 'Gulielmus']],
        [['Gray', 'Grey'], ['Henry']],
        [['Gray', 'Grey'], ['Jane', 'Jana']],
        [['Guanget', 'Guangetus'], ['Delphinat']],
        [['Haller'], ['Wolfgang', 'Wolf']],
        [['Happel', 'Happelius'], ['Wigand']],
        [['Hartung'], ['Johannes', 'Johann']],
        [['Hauser', 'Hauss'], ['Joseph']],
        [['Herdesianus', 'Herdessianus', 'Hardesheim'], ['Christoph']],
        [['Herold'], ['Michael', 'Michel']],
        [['Hohensax', 'von Hohensax', 'Sax'], ['Ulrich', 'Ulrich Philipp', 'Philipp']],
        [['Holzwart'], ['Mathias', 'Matthias']],
        [['Hooper'], ['Anne', 'Anna']],
        [['Hooper', 'Hopper'], ['John']],
        [['Horn', 'Horne'], ['Robert']],
        [['Hospinian', 'Wirth'], ['Johannes']],
        [['Hotman', 'Hotmann', 'Hotomann', 'Hotomannus'], ['François', 'Francois', 'Franz', 'Franziskus', 'Franciscus', 'Franziscus']],
        [['Hubenschmid'], ['Kaspar', 'Caspar']],
        [['Hubert', 'Huprecht'], ['Konrad', 'Conrad']],
        [['Hug', 'Hugo', 'Hug(o)'], ['Johannes', 'Johann', 'Johannes II.']],
        [['Hug', 'Hugo', 'Hug(o)'], ['Johannes d.J.', 'Johannes der Jüngere']],
        [['Humphrey'], ['John Laurence', 'Laurence']],
        [['Hussar', 'Huszár'], ['Gallus', 'Gál']],
        [['Hyperius', 'Gheeraerdts'], ['Laurentius']],
        [['Jaske', 'Jaskeus'], ['Johannes']],
        [['Jeger', 'Jegerus', 'Jäger', 'Jägerus'], ['Isaak', 'Jsaak']],
        [['Jonvilliers', 'Jonvillaeus'], ['Charles', 'Carolus']],
        [['Kaufmann', 'Emporus'], ['Hieronymus']],
        [['Keller', 'Cellarius'], ['Georg', 'Josua']],
        [['Kessler'], ['Johannes', 'Josua']],
        [['Kiszka'], ['Johannes', 'Jan']],
        [['Klösel', 'Khlesl'], ['Anton']],
        [['Kranz', 'Sertorius'], ['Hieronymus']],
        [['Krowicki', 'Crovitius'], ['Martin']],
        [['Kunheim', 'Kunhaim', 'Künhaim', 'von Kunheim', 'von Kunhaim', 'von Künhaim'], ['Erhard']],
        [['König', 'Regius'], ['Nikolaus']],
        [['König von Polen', 'König'], ['Sigismund II. August', 'Zygmunt II.', 'Sigismund II.', 'Sigismund', 'Zygmunt', 'August']],
        [['Lamb', 'zum Lamb', 'Agninus'], ['Hieronimus', 'Hieronymus']],
        [['von Hessen', 'Landgraf von Hessen'], ['Wilhelm', 'Wilhelm IV.']],
        [['von Hessen', 'Landgraf von Hessen'], ['Philipp']],
        [['a Lasco', 'Lasitius', 'Lasicki', 'Lasicius', 'Laski'], ['Johannes', 'Johann', 'Jan']],
        [['Le Machon', 'Lematzotz'], ['']],
        [['Leith', 'Lecheus'], ['James', 'Jacobus Anglus']],
        [['Lentulo', 'Lentulus'], ['Scipio', 'Scipione']],
        [['Linggi', 'Levinus', 'Linki', 'Laevinus'], ['Heinrich']],
        [['Lismaninus', 'Lismanninus', 'Lismanini', 'Lismanino'], ['Franciscus', 'Francesco', 'Franz']],
        [['Lochmann'], ['Hans Heinrich', 'Heinrich']],
        [['Loyseau', 'Loysamme'], ['O.']],
        [['Lydius'], ['Martin', 'Martinus']],
        [['Magius', 'Maggi'], ['Vincentius', 'Vincenzo']],
        [['Mainardi', 'Mainard', 'Mainardo', 'Mainardus'], [ 'Agostino', 'Augustin', 'Augustinus']],
        [['Maler', 'Pictorius'], ['Josua']],
        [['Marcuard'], ['Blaise', 'Blasius']],
        [['Marti', 'Aretius'], ['Benedikt']],
        [['Martinengo', 'Martinengus', 'Martinenghi'], ['Ulysse', 'Ulysses', 'Ulisse', 'Ulisses']],
        [['Martinengo', 'Martinenghi', 'Martinengus'], ['Celso', 'Celsus']],
        [['Matthäus', 'Matthaeus'], ['Johannes Heinrich', 'Joahnnes']],
        [['May'], ['Claudius', 'Glado']],
        [['Menscheverus', 'Menschever', 'Menscheverus Frisius Groningensis'], ['Heinrich', 'Henricus']],
        [['Milander', 'Eppelmann'], ['Engelbert']],
        [['Mommer', 'Mommerus'], ['Aegidius']],
        [['Mont', 'Montius', 'Mundt'], ['Christoph', 'Christopher', 'Christopherus']],
        [['Moranges', 'Morangius'], ['Guy']],
        [['Mortius', 'de Niort'], ['Detus', 'Odet']],
        [['Müller'], ['Georg Jörg', 'Georg', 'Jörg']],
        [['Myliagrius', 'Rietmüller'], ['Jacobus']],
        [['Myszkowski', 'Miszkowski'], ['Stanislaus', 'Stanislaus Czikowski']],
        [['Müsch', 'Müschius'], ['Johannes']],
        [['Naogeorgus', 'Naogeorg', 'Kirchmaier', 'Kirchmeier', 'Kirchmair', 'Neubauer'], ['Thomas']],
        [['Niger', 'Negri'], ['Franciscus']],
        [['Nägeli', 'Näegelin'], ['Christian']],
        [['Obrecht', 'Obprecht', 'Olprech'], ['Georg', 'Jerg']],
        [['Olevianus'], ['Kaspar', 'Caspar']],
        [['Olisleger', 'von Baars', 'Baars', 'a Baars', 'Bars', 'von Baar', 'de Bars'], ['Adolph', 'Adolphus', 'Adolf']],
        [['Oporin', 'Oporinus'], ['Johannes']],
        [['Orth', 'Orthius'], ['Wigand']],
        [['Ott', 'Ottheinrich'], ['Heinrich']],
        [['Paceus'], ['Valentin', 'Valentinus']],
        [['Paclesius', 'Paklepka'], ['Stanislaus']],
        [['Parisotus', 'Parisotti', 'Bergomas'], ['Petrus', 'Pietro']],
        [['Paulus', 'Paul', 'Pawel', 'Pauli', 'Paweł'], ['Gregor', 'Gregorz', 'Gregorius']],
        [['Payan', 'Payanus'], ['Jean', 'Johannes']],
        [['Pellikan', 'Pellican'], ['Konrad', 'Conrad']],
        [['Perusinus', 'Bizzarri'], ['Petrus']],
        [['von der Pfalz', 'Pfalzgraf', 'Pfalzgraf am Rhein', 'Pfalzgraf bei Rhein'], ['Friedrich III.', 'Friedrich']],
        [['Pfister', 'Artopoeus'], ['Nikolaus', 'Nicolaus', 'Baling']],
        [['Philippin', 'Philippinus'], ['Elias', 'Elie']],
        [['Plançon', 'Plancon', 'Plancius'], ['Guillaume', 'Guilelmus']],
        [['Pluna'], ['Jacob Martin', 'Jakob Martin']],
        [['Portus', 'Porto'], ['Franciscus', 'Francesco']],
        [['Poullain', 'Polanus'], ['Valérand', 'Valerandus']],
        [['Pournas', 'Pornaxius'], ['Leonhard', 'Leonhart', 'Léonard', 'Leonhardus', 'Leonarthus']],
        [['Prazmowski'], ['Andreas', 'Andrzej']],
        [['Radziwill', 'Radziwil', 'Radziwiłł', 'Czarny', 'Graf von Wilna'], ['Nikolaus', 'Mikołaj', 'Olika']],
        [['Ramus', 'de la Ramée'], ['Petrus', 'Pierre', 'Peter']],
        [['Rappoltstein', 'von Rappoltstein', 'von Rappoltsweiler'], ['Anna Alexandria', 'Anna', 'Alexandria']],
        [['Rivarius'], ['François', 'Franciscus', 'Francois', 'Franz']],
        [['Roll', 'Rollius'], ['Nikolaus', 'Nicolaus']],
        [['Roset'], ['Michael', 'Michel']],
        [['Ruffus', 'Ruffy'], ['Jacobus']],
        [['Rupe', 'de la Roche Chandieu', 'Chandeus'], ['A.', 'Antoine']],
        [['Russel', 'Bedford'], ['Francis', 'Franciscus', 'Earl of']],
        [['Rust', 'Rust Bernas'], ['Thüring', 'Turingius']],
        [['Röichli', 'Röusch'], ['Jesajas', 'Jesaias', 'Isaia']],
        [['Rüeger'], ['Jakob', 'Jacob']],
        [['Sarnicius', 'Sarnicki', 'Stadnicki'], ['Stanilaus', 'Stanislaw']],
        [['Schenck', 'Schenk', 'Schenkius'], ['Mathias', 'Matthias']],
        [['Schneeberger'], ['Anton', 'Antonius']],
        [['Schnyder', 'Sartorius'], ['Abraham']],
        [['Schöpf', 'Schöpfius'], ['Thomas']],
        [['Schuler', 'Hauptmann Schuler'], ['Fridolin', 'Fridli']],
        [['Schuler'], ['Paul', 'Paulus']],
        [['Sailer', 'Seiler'], ['Gereon']],
        [['Simburger', 'Süburger'], ['Anton', 'Antonius']],
        [['Skalich', 'Scalich', 'Scalichius'], ['Paul', 'Paulus']],
        [['Socin', 'Sozin', 'Sozzini'], ['Laelius', 'Lelio']],
        [['Serin', 'Soerin', 'Soerinus'], ['Leonhard', 'Leonhart']],
        [['Steiger'], ['Johannes', 'Johann', 'Hans']],
        [['Stephan', 'Štefan'], ['Andreas', 'Ondřej']],
        [['Stephanus', 'Estienne'], ['Robert']],
        [['Stokar', 'Stockar', 'Stockarum'], ['Benedikt']],
        [['Strigelius'], ['Victor', 'Victorinus']],
        [['Stuart', 'Sieur de Vézines'], ['Guillaume']],
        [['Stumpf'], ['Johannes Rudolf', 'Johannes', 'Johann', 'Hans', 'Rudolf', 'Johann Rudolf', 'Hans Rudolf']],
        [['Szichzovinus', 'Szikszoi'], ['Lukas', 'Lukács']],
        [['Sägisser', 'Segesser'], ['Albrecht']],
        [['Taffin', 'Tafimus'], ['Jean', 'Johannes']],
        [['Tarnowicz', 'Tarnowski'], ['Johannes']],
        [['Taurus', 'Stier'], ['Sigismund']],
        [['Terentianus', 'Santerentianus', 'Santerrentianus'], ['Julius', 'Iulius']],
        [['Theodor', 'Dietrich'], ['Philipp']],
        [['Thomann', 'Thoman'], ['Heinrich']],
        [['Thoman', 'Thomann'], ['Gregor', 'Gregorius']],
        [['Thyenaeus', 'de Thienes', 'Thienes'], ['Odeardus', 'Odoardus', 'Edouard', 'Eduard']],
        [['Tossanus', 'Toussain'], ['Daniel']],
        [['Toxites', 'Schütz'], ['Michael']],
        [['Traheron'], ['Bartholomäus', 'Bartholomew', 'Bartholomaeus']],
        [['Tschudi'], ['Ägidius', 'Aegidius', 'ägidius', 'Gilg']],
        [['Tuffan', 'Tufanus'], ['Guillaume']],
        [['Uchanski', 'Uchanius'], ['Jakub']],
        [['Ulmer', 'von Ulm'], ['Johann Konrad', 'Johann Conrad', 'Johannes Konrad', 'Johannes', 'Johann', 'Konrad', 'Conrad']],
        [['Utenhove'], ['Johannes', 'Jan']],
        [['von Stetten', 'Stetten'], ['Georg']],
        [['von Stetten', 'Stetten'], ['Georg der Jüngere', 'Georg d.J.']],
        [['Venetscher'], ['Peter', 'Petrus']],
        [['Vergerius', 'Vergerio'], ['Petrus Paulus', 'Pietro Paolo', 'Pietro Paollo', 'Pier Paolo', 'Pier Paollo', 'Pier', 'Petrus', 'Petro', 'Paolo', 'Paulus', 'Paullo']],
        [['Vermigli'], ['Peter Martyr', 'Petrus Martyr', 'Peter', 'Petrus', 'Martyr']],
        [['Viret'], ['Pierre', 'Peter']],
        [['Vitrelin', 'Vitrelinus', 'Witrelin'], ['Alexander']],
        [['Vogel', 'Avienus'], ['Jakob']],
        [['Vogler'], ['Hans', 'Johann', 'Johannes']],
        [['Vogt'], ['Simprecht', 'Simpert']],
        [['Waidner', 'Hertin'], ['Katharina']],
        [['Waidner', 'Waydner', 'Weidner'], ['Wolfgang']],
        [['Weidner', 'Vueydnerus'], ['Johannes']],
        [['Willer', 'Wüller'], ['Georg', 'Jörg']],
        [['Wirth', 'Hospinian'], ['Adrian']],
        [['Wisamer'], ['Baptist Johannes', 'Babt. Johannes', 'Baptist', 'Johannes']],
        [['Wissenburg', 'Wißenburg'], ['Wolfgang']],
        [['Withers', 'Witherus'], ['George', 'Georges', 'Georg']],
        [['Wolfhard', 'Wolfhart'], ['Ulrich']],
        [['Wunderlich', 'de Merveilleux'], ['Hans', 'Jean']],
        [['Wüst', 'Turpilius', 'Zollicovensis'], ['Klaus', 'Nicolaus', 'Nikolaus']],
        [['Xylander', 'Holzmann'], ['Wilhelm']],
        [['Zacius', 'Zak'], ['Simon']],
        [['Zanchi', 'Zanchus', 'Zanchius'], ['Hieronymus', 'Hieronimo', 'Girolamo']],
        [['Zehnder', 'Zehender'], ['Samuel']],
        [['Zurkinden', 'Zerchintes', 'Zitinius'], ['Nikolaus']],
        [['a Belloloco', 'de Beaulieu', 'Belloloco', 'Beaulieu'], ['Hektor', 'Eustorgius']],
        [['de Bellièvre', 'de Bellievre', 'sieur de Hautefort'], ['Jean']],
        [['de Bourbon', 'Bourbon'], ['Henry', 'Henri']],
        [['de Bourbon', 'Bourbon'], ['Louis', 'Loius Ier']],
        [['de Bourbon', 'Bourbon', 'de Condé', 'Condé'], ['Antoine']],
        [['de Coligny', 'Chastillon'], ['Gaspard']],
        [['de Cougnée', 'de Cougnées', 'Le Vasseur'], ['Antoine', 'Jacques']],
        [['de Museau', 'Musaeus'], ['Antoine Morelet', 'Maurus', 'Mauritius']],
        [['de Poix Séchelles', 'sieur de Séchelles'], ['Jean']],
        [['de l’Aubespine'], ['Sébastien', 'Sebastian']],
        [['sr. de Beauvoir-La Nocle', 'Perrucel'], ['Jean de la Fin', 'François, dit de la Rivière']],
        [['von Dörnberg', 'von Dürnberg', 'Dürnberg', 'Dörnberg'], ['Adolf Wilhelm', 'Adolf', 'Wilhelm']],
        [['von Mülinen', 'von Mülynen', 'Mülinen', 'Mülynen'], ['Beat Ludwig', 'Beat', 'Ludwig']],
        [['von Rappoltstein', 'von Heideck', 'Rappoltstein', 'Heideck'], ['Elisabeth', 'Else']],
        [['von Württemberg', 'von Württemberg-Mömpelgart', 'Württemberg', 'Württemberg-Mömpelgart'], ['Georg']],
        [['von der Pfalz', 'Pfalzgraf am Rhein'], ['Friedrich III.', 'der Fromme']],
        [['Öchsli', 'Bovillus'], ['Blasius']],
    ]

    PLACES = [
        ["Aarau"],
        ["Aarburg"],
        ["Aarwangen"],
        ["Aeugst"],
        ["Allgäu"],
        ["Altdorf"],
        ["Altenklingen"],
        ["Altnau"],
        ["Altstätten"],
        ["Amberg"],
        ["Anno"],
        ["Antorff"],
        ["Antwerpen"],
        ["Augsburg"],
        ["Auschwitz"],
        ["Backnang"],
        ["Baden", "Oberbaden", "Ober-Baden"],
        ["Baden-Baden"],
        ["Balgach"],
        ["Balingen"],
        ["Balzheim"],
        ["Basel"],
        ["Baxterley"],
        ["Bedford"],
        ["Belp"],
        ["Bem"],
        ["Berg"],
        ["Berg am Irchel"],
        ["Bergamo"],
        ["Bergell"],
        ["Berleburg", "Berlaburg"],
        ["Berlin"],
        ["Bern"],
        ["Bernang"],
        ["Bernhausen"],
        ["Betschwanden"],
        ["Biberach"],
        ["Biberstein"],
        ["Bichau"],
        ["Biecz"],
        ["Biel"],
        ["Bischofszell"],
        ["Bishopstorpe"],
        ["Blaubeuren"],
        ["Bocksberg"],
        ["Bologna"],
        ["Bonn"],
        ["Boppelsen"],
        ["Borssum"],
        ["Bourges"],
        ["Bradgate"],
        ["Bremen"],
        ["Bremgarten"],
        ["Brescia"],
        ["Breslau"],
        ["Brest", "Brest-Litowsk"],
        ["Brugg"],
        ["Bubikon"],
        ["Buchs"],
        ["Burg Hohen-Aschau"],
        ["Burg Rheinfelden"],
        ["Burg Tarnow"],
        ["Burgund"],
        ["Burtenbach"],
        ["Buschhoven"],
        ["Bußnang"],
        ["Böblingen"],
        ["Böhmen"],
        ["Bülach"],
        ["Bünden"],
        ["Calcinato"],
        ["Calvidum"],
        ["Cambridge"],
        ["Casaccia"],
        ["Caspano"],
        ["Český"],
        ["Cham"],
        ["Chambéry"],
        ["Chavannes"],
        ["Chiavenna"],
        ["Chur"],
        ["Châtillon", "Châtillon-sur-Loing"],
        ["Colmar"],
        ["Compagnie"],
        ["Coventry"],
        ["Cremona"],
        ["Danzig"],
        ["Davos"],
        ["Debrezin"],
        ["Dießenhofen", "Diessenhofen"],
        ["Domleschg"],
        ["Donauwörth"],
        ["Dover"],
        ["Dresden"],
        ["Dubiecko", "Dubiecz"],
        ["Duisburg"],
        ["Durham"],
        ["Dürnten"],
        ["Eglisau"],
        ["Eibenschitz"],
        ["Eichstätt"],
        ["Elgg"],
        ["Elsass"],
        ["Ely"],
        ["Embrach"],
        ["Emden"],
        ["Entringen"],
        ["Eppingen"],
        ["Erbach"],
        ["Erfurt"],
        ["Erlenbach"],
        ["Esslingen"],
        ["Farnham Castle"],
        ["Fehraltorf"],
        ["Feiburg"],
        ["Feldlager"],
        ["Ferrara"],
        ["Fideris"],
        ["Fischingen"],
        ["Forstegg"],
        ["Frankenthal"],
        ["Frankfurt", "Frankfurt am Main"],
        ["Frauenfeld"],
        ["Freiburg"],
        ["Friedberg"],
        ["Friedewald"],
        ["Frzeslawicz"],
        ["Fulham"],
        ["Füssen"],
        ["Gachnang"],
        ["Genf"],
        ["Gernersheim"],
        ["Gerzensee"],
        ["Giengen"],
        ["Gilford"],
        ["Girenbad"],
        ["Glarus"],
        ["Gloucester"],
        ["Gossau"],
        ["Graubünden"],
        ["Greenwich"],
        ["Grießenberg", "Grießenbergi", "Griessenberg", "Griesenberg"],
        ["Groningen"],
        ["Grönenbach"],
        ["Grüningen"],
        ["Guildford"],
        ["Gundelfingen", "Gundelfingen an der Donau"],
        ["Gunzenhausen"],
        ["Gyrenbad"],
        ["Gyrsberg"],
        ["Gyula"],
        ["Göppingen"],
        ["Görlitz"],
        ["Güttingen"],
        ["Hagenau"],
        ["Haldenstein"],
        ["Hall", "Hall in Tirol"],
        ["Hallwil"],
        ["Hamburg"],
        ["Handschuhsheim"],
        ["Hausen"],
        ["Hedelfingen"],
        ["Heideck"],
        ["Heidelberg"],
        ["Heiningen"],
        ["Herisau"],
        ["Hessen"],
        ["Hettingen"],
        ["Hinwil"],
        ["Hirzel"],
        ["Hohentwiel"],
        ["Holborn"],
        ["Homberg"],
        ["Hona"],
        ["Horburg"],
        ["Horgen"],
        ["Horn"],
        ["Hotteln"],
        ["Hunaweier"],
        ["Hundwil"],
        ["Höchstädt", "Höchstädt an der Donau"],
        ["Höngg"],
        ["Imola"],
        ["Ingolstadt"],
        ["Innsbruck"],
        ["Irchel"],
        ["Isny"],
        ["Iwanowicz", "Ivanowicz", "Iwanowicze"],
        ["Jenins"],
        ["Jonschwil"],
        ["Justingen"],
        ["Kalden"],
        ["Kappel", "Kappel am Albis"],
        ["Kassel"],
        ["Kaufbeuren"],
        ["Kempten"],
        ["Kilchberg"],
        ["Kirchberg"],
        ["Kleck"],
        ["Klettgau"],
        ["Kloten", "Rohr bei Kloten"],
        ["Kolding"],
        ["Konstanz"],
        ["Kopenhagen"],
        ["Krafftheim"],
        ["Krakau"],
        ["Kronstadt"],
        ["Krumau"],
        ["Krumlov"],
        ["Krummenau"],
        ["Kuenshein"],
        ["Kyburg"],
        ["Köln"],
        ["Königsberg"],
        ["Königsfelden"],
        ["Küsnacht"],
        ["La Rochelles", "La Rochelle", "Rochelle", "Rochelles"],
        ["Lambeth"],
        ["Landshut"],
        ["Langenthal"],
        ["Laufen"],
        ["Lauingen"],
        ["Lausanne"],
        ["Lavin"],
        ["Leeder"],
        ["Leipzig"],
        ["Lenzburg"],
        ["Leslau"],
        ["Leutmerken"],
        ["Lichtenberg"],
        ["Lichtensteig"],
        ["Ligerz"],
        ["Lindau"],
        ["Litopolis"],
        ["Litowsk"],
        ["Locarno"],
        ["Lohrbach"],
        ["London", "London-Lambeth"],
        ["Lublin"],
        ["Ludham"],
        ["Luzern"],
        ["Lyon"],
        ["Lübeck"],
        ["Magdeburg"],
        ["Maggiatal"],
        ["Maienfeld"],
        ["Mailand"],
        ["Mainz"],
        ["Malans"],
        ["Manslacht"],
        ["Marbach"],
        ["Marburg"],
        ["Martiliasi"],
        ["Maschwanden"],
        ["Maulbronn"],
        ["Maur"],
        ["Meilen"],
        ["Melschtin"],
        ["Melsungen"],
        ["Memmingen"],
        ["Mesericz"],
        ["Metz"],
        ["Misox"],
        ["Mittelstetten"],
        ["Moers"],
        ["Moldau"],
        ["Montbéliard"],
        ["Montpellier"],
        ["Morbegno"],
        ["Morges"],
        ["Mosbach"],
        ["Mödingen"],
        ["Mömpelgard"],
        ["Mömpelgart"],
        ["Mülhausen"],
        ["München"],
        ["Neuburg", "Neuburg an der Donau"],
        ["Neuenburg"],
        ["Neumarkt"],
        ["Neunform", "Oberneunform", "Ober-Neunform", "(Ober-)Neunform"],
        ["Neunkirch"],
        ["Niederhone"],
        ["Niederurnen"],
        ["Niederweningen"],
        ["Norden"],
        ["Norwich"],
        ["Nozereth"],
        ["Nozeroy"],
        ["Nyon"],
        ["Nîmes", "Nimes"],
        ["Nördlingen"],
        ["Nürnberg"],
        ["Oberglatt"],
        ["Oberlausitz"],
        ["Oldersum"],
        ["Oransko"],
        ["Orbe"],
        ["Orléans"],
        ["Orthius"],
        ["Osnabrück"],
        ["Osseko"],
        ["Osweczin"],
        ["Oswiecim"],
        ["Otelfingen"],
        ["Othmarsingen"],
        ["Ottenbach"],
        ["Oxford"],
        ["Padua"],
        ["Paris"],
        ["Payerne"],
        ["Pelsnica", "Pelsnicze"],
        ["Petrikau"],
        ["Pewsum"],
        ["Pfalz"],
        ["Pforzheim"],
        ["Pfyn"],
        ["Pinczow"],
        ["Pinegow"],
        ["Plurs"],
        ["Poissy"],
        ["Polen"],
        ["Pontresina"],
        ["Posonium"],
        ["Promontogno"],
        ["Przeslawicz"],
        ["Puschlav"],
        ["Querceto"],
        ["Radziejow"],
        ["Rafz"],
        ["Ramsen"],
        ["Rappoltstein"],
        ["Rappoltsweiler", "Rappoldsweiler"],
        ["Rappoltweiler"],
        ["Rauschenberg"],
        ["Ravensburg"],
        ["Regensburg"],
        ["Reichenweier"],
        ["Reutlingen"],
        ["Rheinau"],
        ["Rheineck"],
        ["Rheinfelden"],
        ["Richmond"],
        ["Rickenbach"],
        ["Ringgen"],
        ["Rohr"],
        ["Rohrenfels"],
        ["Rolle"],
        ["Rom"],
        ["Romrath"],
        ["Rostock"],
        ["Roth"],
        ["Rothenstein"],
        ["Rottenstein"],
        ["Rottweil"],
        ["Rumänien"],
        ["Ruremond"],
        ["Russikon"],
        ["Rötteln"],
        ["Rüti"],
        ["Saanen"],
        ["Sachsen"],
        ["Saint-Germain"],
        ["Salisbury"],
        ["Samaden"],
        ["Schaffhausen"],
        ["Schafis"],
        ["Scharfenort"],
        ["Scherzingen"],
        ["Scherzligen"],
        ["Schlachteck"],
        ["Schleiden"],
        ["Schlesien"],
        ["Schleusingen"],
        ["Schopfheim"],
        ["Schramberg"],
        ["Schwanden"],
        ["Schweiz"],
        ["Secomini"],
        ["Sem"],
        ["Sendomir"],
        ["Siebenbürgen"],
        ["Siena"],
        ["Sils im"],
        ["Sittaw"],
        ["Sitten"],
        ["Solangio"],
        ["Solothurn"],
        ["Sondrio"],
        ["Spangenberg"],
        ["Speier"],
        ["Speyer"],
        ["St. Gallen"],
        ["St. Germain"],
        ["St. Germain en Laye"],
        ["St. Margrethen"],
        ["St. Peterzell"],
        ["St. Poissy"],
        ["Stackboren"],
        ["Stammheim"],
        ["Steckborn"],
        ["Steeg"],
        ["Stein"],
        ["Stein am Rhein"],
        ["Strassburg"],
        ["Straßburg"],
        ["Stuttgart"],
        ["Suhr"],
        ["Süs"],
        ["Tarnow"],
        ["Tegerfelden"],
        ["Thetford"],
        ["Thun"],
        ["Thüringen"],
        ["Tirano"],
        ["Tirol"],
        ["Toggenburg"],
        ["Tomice"],
        ["Torgau"],
        ["Töß"],
        ["Tübingen"],
        ["Ulm"],
        ["Urach"],
        ["Urdorf"],
        ["Uri"],
        ["Uster"],
        ["Veltheim"],
        ["Veltlin"],
        ["Venedig"],
        ["Vicosoprano"],
        ["Voras"],
        ["Vézelay"],
        ["Wagegg"],
        ["Walachei"],
        ["Walenstadt"],
        ["Waltenhofen"],
        ["Warschau"],
        ["Wartau"],
        ["Wasenberg"],
        ["Wattwil"],
        ["Wechingen"],
        ["Weinfelden"],
        ["Weinheim"],
        ["Wesel"],
        ["Westminster"],
        ["Wetter"],
        ["Wetzikon"],
        ["Wieliczka"],
        ["Wien"],
        ["Wiesendangen"],
        ["Wigoltingen"],
        ["Wildenberg"],
        ["Wilna"],
        ["Winchester"],
        ["Windsor"],
        ["Winterthur", "Oberwinterthur", "Ober-Winterthur"],
        ["Wittenberg"],
        ["Wlodislaw", "Wlodzislaw", "Wodzislaw", "Włocławek"],
        ["Wolfsheim"],
        ["Wolp"],
        ["Worcester"],
        ["Woringen"],
        ["Worms"],
        ["Wädenswil"],
        ["Wülflingen"],
        ["Württemberg"],
        ["Xions"],
        ["York"],
        ["Zaliczin"],
        ["Zapfenburg"],
        ["Zator"],
        ["Ziegenhain"],
        ["Zittau"],
        ["Znaim"],
        ["Zofingen"],
        ["Zollikon"],
        ["Zug"],
        ["Zuoz"],
        ["Zurzach"],
        ["Zürich"],
        ["Zürich-Neumarkt"],
    ]
